### ISSUE TITLE
Link selector is duplicating links in Firefox

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#1001]
Create a page in Firefox
Drag and drop a content block widget
Type some text in it
Mark the text
Open the link selector
Insert a link to webpage
As a result: the text is duplicated
//If you try to edit the link and press insert - the link is duplicated
//If you insert an image as link and edit - the image is duplicated

**Comment by dzhenko** [comment]
If you debug the sf-html-field.js (line 60), the text/image is not doubled.

**Comment by PepiIvanova** [comment]
should be tested for all browsers - IE, FF and Chrome
