### ISSUE TITLE
Image, Document Selector: "No images"/"No documents" message appears for libraries on root level in List View

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#1004]
1. Upload some images/documetns in library on the root level, for example Default Library
2. Open feather image/document selector and switch to List View
3. filter by "All Libraries"
Note that No images/documents appears in the grid for the library (http://screencast.com/t/ZMWeFcyGk3)
Expected: no label with item count should be present

**Comment by GeorgiMateev** [comment]
the fix related to #1060 and are on the same branch

**Comment by GeorgiMateev** [comment]
At the moment the fix will be only for the document selector.
