### ISSUE TITLE
You are not able to add avatar in Firefox if the user has no image

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#1005]
Navigate page with profile widget // the user must not have an avatar
Click to upload an image and save
As a result: the avatar is not applied
//If you already have an image you are able to change it

**Comment by Boyko-Karadzhov** [comment]
The issue is with the browser feature "Remember password" after changing a password. It will type in a value for "Old password" that will cause a validation and that validation will fail.
