### ISSUE TITLE
Do you publish the symbol files of the feather libraries somewhere?

### ISSUE THREAD

**Issue by AlexandreRoba** [Sitefinity/feather#1021]
I'm struggling with a Feather features. I need to debug the assembly. Can I find the Symbol server for the Telerik.SiteFinity.Feather.core.1.1.70.1 somewhere?

Thanks for any help.

**Comment by Tihomir-Petrov** [comment]
Hi AlexandreRoba,

You can get the Feather pdb files by dowloading and building the source code for version 1.1.70.1. You can download the source code for this version via the release tag v.1.1.70.1 : https://github.com/Sitefinity/feather/releases/tag/v.1.1.70.1 or directly via the following link https://github.com/Sitefinity/feather/archive/v.1.1.70.1.zip .

Hope this helps.

**Comment by AlexandreRoba** [comment]
Hi Tihomir-Petrov,

thanks for the information. I was expecting to be able to found the PDB files that were generated during the compilation. This would enable us to open one file of the source code from feather on visual studio set a break point and debug... Having to download the code to compile ourselves force us to then replace the assembly that are installed with the Nuget.
Just an idea: the Pdb could be included on the Nuget or could be posted to sites such as Symbolsource.org and referenced from the Nuget. This would simplify our debugging experience :)

Regards,

Alex.

**Comment by Tihomir-Petrov** [comment]
Hey Alex,

We discussed your request and we decided to work on it and to ship it in some of the next releases of Feather.

Kind Regards,
Tisho

**Comment by ElenaGaneva** [comment]
Hello Alex, 

Since now the pdbs are available with the Sitefinity I am closing this issue.

Regards,
Elena
