### ISSUE TITLE
LoginForm: you are not able to login with already logged in user if remember me option is checked

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#1029]
Add login form to page and enable remember me option
Publish the page
Navigate to the frontend as logged in user
Perform a login
Navigate the login page in another browser
Make sure that remember option is checked
Try to login with the same user
As a result: you are not redirected to the self logout page
//The old widget is working in spite of this option

**Comment by ElenaGaneva** [comment]
This is fixed with latest versions of Sitefinity 11.0+ so i am closing this issue

Regards,
Elena
