### ISSUE TITLE
Document selector: dimensions in tooltip is missing

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#1043]
![image](https://cloud.githubusercontent.com/assets/234207/6708599/6e78fb9e-cd7a-11e4-99fa-0b6e171aa0be.png)

**Comment by NadezhdaPetrova** [comment]
Also by UX the last property must be Created on: http://ux.sitefinity.com/Sitefinity%20Feather/#p=document_selector

**Comment by NadezhdaPetrova** [comment]
If the file size is < 1KB the show size is 0. This is because of the sitefinity service
