### ISSUE TITLE
Search results: language links for search results are not working on SemanticUI

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#1065]
site is in ML: English (default) and Spanish
Create a news item in both languages
Create a page with news widget in both languages
Create a search index for all content
Create a page based on SemanticUI with search results widget in both languages
Create a page with search box widget and select the search index and the search results page
Navigate the page with the search box and search for news
On the results page try to switch results between languages
As a result: the links are not making any request - http://screencast.com/t/wugwQWdZOeB

**Comment by ElenaGaneva** [comment]
We no longer support Semantic package, so I am closing this issue.

Regards,
Elena
