### ISSUE TITLE
You are not able to register new user if requiresQuestionAndAnswer is enabled

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather#1070]
1. Enable requiresQuestionAndAnswer in Advanced settings > Security > Membership provider settings
2. Create a page
   Drag and drop Registration widget on it
3. Publish the page and navigate the page on the frontend
4. Try to register new user

Actual result is: The user cannot be registered 

Please enter a different security answer.

**Comment by ElenaGaneva** [comment]
This issue is not reproducible with latest Sitefinity 11.0+ so I will close this issue.

Regards,
Elena
