### ISSUE TITLE
Document Selector: During upload all buttons are active, pressing sometimes Upload button is causing Sitefinity to crash

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#1077]
In Content Block - > Document selector start upload big file, for example 200MB
During upload note all buttons are active and this cause the following problems:
1. Cancel is not stopping the upload request, you are returned to the selector dialog, but still the request is running in the console
2. Pressing many times Upload button is causing many requests to appear and finally everything stuck, many selectors become broken, content block become broken too.
Solution: Buttons should be disabled or should not be visible at all

**Comment by mirinka** [comment]
Reop: in foundation template - X and Cancel button are not visible during upload (see screenshot: http://screencast.com/t/RF7LL1jmGJgU)

**Comment by SlaveyaShtereva** [comment]
Still you can change title, add categories and tags during upload, but this changes are not applied. These actions also should be blocked
