### ISSUE TITLE
Profile: js error message appears if you try to add avatar with incorrect extension

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#1080]
Ina page with profile widget, for avatar choose a file with incorrect extension (.zip for example)
Note that nothing happend, but js error message is available in the console:
Uncaught RangeError: Invalid string length fileInput.on.reader.onload

**Comment by GeorgiMateev** [comment]
Now there is no js error, only "Edit is not allowed! " appears. There is already an issue for inprovement of this validation.
