### ISSUE TITLE
Login/Logout button: login status is not updated even when page caching is disabled

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#1103]
Create a page and in advance settings on page create select No caching
Add login form and login status on this page
Navigate the page
Logout from login status widget
Login another user using login form
As a result: login status is not updated and you still see Login and register links

//there is a client cache from the browser

**Comment by GeorgiMateev** [comment]
The bug is reproducable in Internet explorer, when the debug tools (F12) are closed.
