### ISSUE TITLE
Grid: Upgrade script for grid widgets

### ISSUE THREAD

**Issue by Tihomir-Petrov** [Sitefinity/feather#1125]

**Comment by Boyko-Karadzhov** [comment]
Testing:
1. Start with blank Sitefinity project (no resource packages);
2. Install Feather 1.2.130 (make sure ResourcePackages folder is not there);
3. Observe that "Bootstrap grid widgets" section is present when editing Page (Layouts tab);
4. Turn off the web application (iisreset);
5. Put the packages into the ResourcePackages folder;
6. Download latest Feather source, change its version to 1.2.140 and build;
7. Replace the DLLs in the web app and navigate to backend;
8. Observe that there is one section for each package in the toolbox; See ToolboxConfig and make sure there is no section with name "HtmlLayouts";
