### ISSUE TITLE
Breakpoints does not work in View when feather is enabled

### ISSUE THREAD

**Issue by lovleen** [Sitefinity/feather#1139]
Hi there,

As soon as feather is installed, breakpoints in MVC view throws an Execute() error. here is the screenshot for thie error.

![secondscreenshot](https://cloud.githubusercontent.com/assets/11654740/6835890/d0b9708c-d391-11e4-8fcb-437df44fc3cb.jpg)

Steps to duplicate this issue:
1.  create a new sitefinity project any version 7.3.5316 or 5320
2.  create a new MVC widget and put breakpoint in VIEW.. All will work fine and you can see your   breakpoint getting hit when you will debug
3.  Now stop debugging and install feather.
4.  try to run your solution and you will see Execute() error in your view

An idea how to fix this issue??

Thanks
Lovleen

**Comment by mariushm** [comment]
Thanks Lovleen,

We have added the issue to our backlog and will consider delivering a fix in one of the upcoming releases.

Mariush

**Comment by jmotes** [comment]
@mariushm Do you have an update on this?

**Comment by incanus0489** [comment]
Hey guys,

Any update on this one?

Amit.

**Comment by daviddupont69** [comment]
Is that point still pending? or solved in latest release? We are still unable to attach in views and feel like working with PHP as soon as we mess with views :-)

**Comment by todorm85** [comment]
This is no longer reproducable following official guidelines on creating MVC widgets https://www.progress.com/documentation/sitefinity-cms/create-widgets-mvc
and enabling debugging of templates in web.config>compilation element.
