### ISSUE TITLE
ScriptHelpers: navigate a page based on template from package results in error 'requirejs is not defined'

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#1156]
Create a page based on bootstrap or some other package
Navigate on the frontend
As a result: requirejs is not defined

**Comment by ElenaGaneva** [comment]
Reporducible on casini.

**Comment by PetyaRachina** [comment]
Except for this issue , also the news widgets styles are not loaded under virtual directory and some other serious issues related to a project running on virtual directory or cassini
