### ISSUE TITLE
Grid widgets: Drag and drop grid widget (e.g Bootstrap) on hybrid page - page is broken

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather#1167]
1. Create hybrid page
2. Drag and drop grid widget on the page (e.g Bootsrap)
3. Publish the page 
4. Navigate the page on the frontend

Actual result is: Page is broken

Server Error in '/' Application.

~/Frontend-Assembly/Telerik.Sitefinity.Frontend/GridSystem/Templates/grid-3+9.html

**Comment by Boyko-Karadzhov** [comment]
This should be handled in Sitefinity.

**Comment by ElenaGaneva** [comment]
Not reproducible with latest 11.0+
