### ISSUE TITLE
Have some problems using media field directive and image field directive

### ISSUE THREAD

**Issue by David-Heylbroeck** [Sitefinity/feather#1170]
I have two issues when I using this directives for both issues there is no error message in the console :
1. I implement the image field directive on a custom widget designerview and it works but when I open the image selector and try to upload a new image, after the selection of the files I can't save it because I don't choice the library but there is no control to select a librairy. 

(![imagefielddirective1](https://cloud.githubusercontent.com/assets/11441783/6851116/55125678-d3dd-11e4-9077-4808bc0f62f3.PNG)
![imagefielddirective2](https://cloud.githubusercontent.com/assets/11441783/6851117/55170484-d3dd-11e4-91ba-c1d63ea9fb3f.PNG)
![imagefielddirective3](https://cloud.githubusercontent.com/assets/11441783/6851119/5518ae24-d3dd-11e4-9ffd-68f577077f3e.PNG))

2. I implement the Media field directive on a custom widget designerview and when I try to edit that field that's open an empty popup.

(![mediafielddirective](https://cloud.githubusercontent.com/assets/11441783/6851118/55175b3c-d3dd-11e4-9a08-b4fef1267b95.PNG))

**Comment by PepiIvanova** [comment]
Regarding image field there is an omission in documentation. In designerview-yourview.js file, right before the definition of custom view controller, you need to inject sfFields and sfSelectors instead of sfImageField:

var designerModule = angular.module('designer');
angular.module('designer').requires.push('sfFields');
angular.module('designer').requires.push('sfSelectors');

**Comment by NadezhdaPetrova** [comment]
Regarding media field directive we did some refactoring that will be released at the end of this week and the documentation will be updated. If you want to use media field directive before the official release of 1.2.160 use the official released Feather version 1.2.150.
