### ISSUE TITLE
ScriptHelpers: page with login status widget is loaded 5 times slower

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#1174]
Add login logout button on a page based on bootstrap
Navigate on the frontend
Check the requests time
Compared to master version it is 5 times slower

http://screencast.com/t/SM2pCfVa
http://screencast.com/t/4CuXsRlHO

**Comment by ElenaGaneva** [comment]
The scripts must be loaded before @Html.InlineEditingManager(false) in order to imporve the performance!
