### ISSUE TITLE
Document link: tooltip position should be fixed

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#1196]
see tooltip icon of documents and images
document's tooltip is a few pixel lower than image's tooltip

documents:
![image](https://cloud.githubusercontent.com/assets/234207/6914747/94a94820-d796-11e4-953a-c93aba3d2121.png)

images:
![image](https://cloud.githubusercontent.com/assets/234207/6914752/a0347ec6-d796-11e4-8af7-eaa6cebf9b31.png)

**Comment by JenPeleva** [comment]
Fixed in Feather - branch ListWidgetStyling
