### ISSUE TITLE
Cannot localize labels for feather widgets

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#1199]
1. Go to Administration > Basic settings and set Deutsch for backend language
2. Go to Administration > Labels and Messages 
3. Find some feather widget secion in the right sidebar, e.g for Search widget
4. Edit some resource and localize Deutsch version
5. Drag and drop widget on a page (Search widget)
6. Open widget designer - as a result: no localization
7. Edit the same resource and localize English version
8. Open widget designer - as a result: English localization is diplayed, although Deutsch is your backend language

video with steps to reproduce:
http://screencast.com/t/bvnuvX2sly0

**Comment by GeorgiMateev** [comment]
It should be noted that if the label is in a client component for example a selector or any other file that ends with .sf-cshtml, the app should be restarted before the change to take effect, because the file is cached.
