### ISSUE TITLE
List Widget: List templates do not appear in the correct order in the dropdown

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#1200]
1. According to the UX templates should appear in the following order in the dropdown:
Simple list
Expanded list
Expandable list
Anchor list
Pages list
The same is the order in the old Sitefinity widget.
In feather templates dropdown order is different and names are different

**Comment by NadezhdaPetrova** [comment]
For now we do not have mechanism to reorder the templates
