### ISSUE TITLE
List Widget: Selecting anchor list template, then clicking on some link in page zone editor is causing js error messages

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#1211]
1. D&D list widget, select a list
2. Select Anchor list template and save
3. In page zone editor click on some anchor link or on "Back to top"
   Note that js errors appear:
   http://screencast.com/t/eIHKouDY

**Comment by ElenaGaneva** [comment]
Not able to reproduce with 11.0+
