### ISSUE TITLE
DocumentList: Extension should be returned without a dot in DocumentsListModel and DocumentDetailsViewModel as it is in DocumentModel

### ISSUE THREAD

**Issue by JenPeleva** [Sitefinity/feather#1214]
Please check the implementation of DocumentModel for GetExtension. The same should be done for DocumentDetails and DocumentList view models.

**Comment by mirinka** [comment]
Reop:
bootstrap - list and table view: still .[extension] appear
bootstrap - details page: still .[extension] appear
