### ISSUE TITLE
List widget: predefined styles does not work

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#1216]
Create some predefined styles for List widget
Open List widget designer
Expand More options
As a result: Style dropdown is not displayed

**Comment by PepiIvanova** [comment]
var simpleViewModule = angular.module('simpleViewModule', ['expander', 'designer', 'sfSelectors']);
    angular.module('designer').requires.push('simpleViewModule');

    simpleViewModule.value('cssClasses', {
        'AnchorList': [
            { 'value': 'blue', 'title': 'Blue box' },
            { 'value': 'red', 'title': 'Red box' }
        ],
        'ExpandableList': [
            { 'value': 'blue', 'title': 'Blue box' },
            { 'value': 'red', 'title': 'Red box' }
        ],
        'ExpandedList': [
            { 'value': 'blue', 'title': 'Blue box' },
            { 'value': 'red', 'title': 'Red box' }
        ],
        'PagesList': [
            { 'value': 'blue', 'title': 'Blue box' },
            { 'value': 'red', 'title': 'Red box' }
        ],
        'SimpleList': [
            { 'value': 'blue', 'title': 'Blue box' },
            { 'value': 'red', 'title': 'Red box' }
        ],
        'DetailPage': [
           { 'value': 'green', 'title': 'Green box' }
        ]
    });
