### ISSUE TITLE
List widget: After publishing list on a page, backend Preview for corresponding list items is not working

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#1220]
1. Create list with list items
2. D&D feahter list widget, select this list, select for example pages list template and publish the page
3. Go to the backend, select some list item for edit and press Preview
Note that "We can't display Preview, because no pages has been set to display content like this" page appears

**Comment by NadezhdaPetrova** [comment]
branch: content-location-service-fix
