### ISSUE TITLE
Video Selector: Play button in missing from video thumbnail in properties dialog

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#1235]
Note that according the UX in video properties dialog play button should be available:
http://screencast.com/t/rNExMCU22svn

**Comment by mirinka** [comment]
Reop: now when you play a video, it is played in full size, but it should be resized 
UX: http://ux.sitefinity.com/Sitefinity%20Feather/#p=video 
now: http://screencast.com/t/KRgvN77QXFDq
