### ISSUE TITLE
Image Gallery: Add option to sort images as they are ordered in the image library

### ISSUE THREAD

**Issue by sabrie** [Sitefinity/feather#1243]
This option is available with the standard built-in Image Gallery widget and it would be great if this can be included as an out of the box option with the MVC Image Gallery widget.

**Comment by ElenaGaneva** [comment]
This feature was added in version [1.4.360.0](https://github.com/Sitefinity/feather-widgets/releases/tag/v.1.4.360.0) . It is available with latest Sitefinity 11.0+ so I am closing this issue.

Regards,
Elena
