### ISSUE TITLE
Navigation does not display child pages if set to a custom selection of pages

### ISSUE THREAD

**Issue by jpspicer** [Sitefinity/feather#1269]
If you use a custom selection of pages instead of top level pages (I haven't tested with other options) child pages are not displayed. If you select the child pages as well they get displayed at the top level and not in a drop down (using the horizontal template). Everything works as expected if I use top level pages.

**Comment by dzhenko** [comment]
Hey @jpspicer, 

We will include this feature in one of our future releases.

Kind Regards,
Dzhenko Penev
