### ISSUE TITLE
Comments plans?

### ISSUE THREAD

**Issue by AlexandreRoba** [Sitefinity/feather#1270]
Hi all, do you have any view today on the implementation of the comments widgets in feather?
Keep doing the good work.

**Comment by Tihomir-Petrov** [comment]
Hi Alex,

The Comments widget is among our top priorities. In this line of thoughts we plan to work on it in the upcoming weeks (IMHO we will ship it within the next 5-6 weeks). On a side note, what are your business requirements regarding the usage of the Comments widgets (e.g. do you plan to use the 'Raitings' functionality)?

Kind Regards,
Tisho

**Comment by AlexandreRoba** [comment]
Hi Tihomir-Petrov,

We need to deliver a working Blog constructor with comments by end of next month. Thos comments will include rating.

As a feature request: it would be great if the users could answer to a comment (at least one level).
Meaning you could see the comments suc as
Comment 1
Comment 2
--Reply to Comment 2
--Another Reply to comment 2
Comment 3
--Reply to Comment 3 

Thi is not absolutly necessary but it would be great if it could be foreseen in a near futur.

regards,

**Comment by Tihomir-Petrov** [comment]
Note that we plan to release the Blogs MVC widget and the Blog post MVC widget prior the Comments MVC widget. Regarding the "reply to comment" functionality, we will need to do changes in the core Sitefinity dlls therefore we will not be able to include it in the release of the Comments MVC widget.

Best,
Tihomir
