### ISSUE TITLE
FrontendControllerFactory and Dependency Injection

### ISSUE THREAD

**Issue by MerrittMelker** [Sitefinity/feather#1275]
Where do you setup bindings for controllers?

I created a derived FrontEndControllerFactory and set it up in a bootstrapper initalized event handler:

ControllerBuilder.Current.SetControllerFactory(factory)

but this stuff:

feather/Telerik.Sitefinity.Frontend/FrontendModule.cs
feather/Telerik.Sitefinity.Frontend/Mvc/Infrastructure/Controllers/ControllerContainerInitializer.cs

 also adds a bootstrapper initalized event handler, which will be added after one added in Application_Start

Also, your FrontendControllerFactory uses a a ninject kernal but gives us no exposure or method to load bindings insofar as I can see. You need to Give us a way to setup IoC for our controllers ,wtf why am I the only one bringing this up ? AM I COMPLETELY MISSING SOMETHING HERE?

=== My Solution ATM
```
public class Global : HttpApplication
{
        private static bool _firstApplicationBeginRequest = true;

        protected void Application_Start(object sender, EventArgs e)
        {
        }

        protected void Session_Start(object sender, EventArgs e)
        {
        }

        protected void Application_BeginRequest(object sender, EventArgs e)
        {
            // Hack: Done Here because Sitefinity isn't designed properly: we can't override there Controller Factory
            if (_firstApplicationBeginRequest)
                ControllerBuilder.Current.SetControllerFactory(new NinjectControllerFactory());
            _firstApplicationBeginRequest = false;
        }
       ....
```
```
public class NinjectControllerFactory : FrontendControllerFactory
    {
        private readonly IKernel _ninjectKernel;

        /// <summary>
        /// Initializes a new instance of the <see cref="NinjectControllerFactory"/> class.
        /// </summary>
        public NinjectControllerFactory()
        {
            _ninjectKernel = new StandardKernel(new InterfaceMappings());
        }

        protected override void Dispose(bool cleanManagedResources)
        {
            if (cleanManagedResources)
                this._ninjectKernel.Dispose();
        }

        /// <inheritdoc />
        protected override IController GetControllerInstance(System.Web.Routing.RequestContext requestContext, Type controllerType)
        {
            return (IController)this._ninjectKernel.Get(controllerType);
        }
    }
```

**Comment by Boyko-Karadzhov** [comment]
Hello Merritt,

We have a documentation article about this: [Constructor dependency injection for controller using Ninject](https://github.com/Sitefinity/feather/wiki/Constructor-dependency-injection-for-controller-using-Ninject)

I have updated the article recently because of the _Bootstrapper.Initialized_ that, as you have mentioned, is not working as expected. You can set the new factory on _Bootstrapper.Bootstrapped_. Thank you for the feedback!

Please let us know if using the _Bootstrapped_ event solves the issue in your project.

Regards,
Boyko

**Comment by MerrittMelker** [comment]
```
protected void Application_Start(object sender, EventArgs e)
{
     Bootstrapper.Bootstrapped += Bootstrapper_Bootstrapped;
}
```

Works... thanks. I still see in the article it pointing to Initialized.

**Comment by Boyko-Karadzhov** [comment]
Thanks Merrit! The article is now up to date.
