### ISSUE TITLE
Video widget: Missing cancel button when upload video on Foundation based page

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather#1315]
1. Create a page based on Foundation template
2. Drag and drop Video widget
3. Upload a video from the Video widget

Actual result is: Cancel button is missing - see attached screen http://screencast.com/t/Js3NKJbMHVu

**Comment by SlaveyaShtereva** [comment]
Reproducible for all media widgets

**Comment by SlaveyaShtereva** [comment]
Also 'X' button is missing
