### ISSUE TITLE
Video widget: Video desapears when switch simple and advance view

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather#1318]
1. Create a page 
2. Drag and drop Video widget on it
3. Select video and save the widget
4. Publish the page
5. Edit the oage and edit the Video widget
6. Switch Simple -> Advance -> Simple -> Advance -> Simple

Actual result is: Video desapears - see attached screen http://screencast.com/t/TVMav7vKYfa

**Comment by ElenaGaneva** [comment]
Improved performanced. Now the issue is happening when you swith tabs more than 5 times(counted more than 5 enterings in "Simple"). The issue that remains is due to a browser behaviour.
