### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#1328]
There doesn't appear to be any docs on creating a new MVC widget and creating a feather designer...thunder generates an ugly webforms designer.

Can someone also please talk to the thunder guys to support this in the extension too?

**Comment by sitefinitysteve** [comment]
I have tried this https://github.com/Sitefinity/feather/wiki/Create-a-custom-designer-view

...but doesn't seem to work?
![image](https://cloud.githubusercontent.com/assets/1542376/7209722/4854b3c0-e519-11e4-814e-b4e07a446ceb.png)

**Comment by sitefinitysteve** [comment]
If I inspect the service call, this is the error and indeed its not even looking in the folder

The partial view 'DesignerView.Simple' was not found or no view engine supports the searched locations. The following locations were searched:
~/Views/Designer/DesignerView.Simple.aspx
~/Views/Designer/DesignerView.Simple.ascx
~/Views/Shared/DesignerView.Simple.aspx
~/Views/Shared/DesignerView.Simple.ascx
~/Frontend-Assembly/SitefinityWebApp/Mvc/Views/ExpertBio/DesignerView.Simple.aspx#OutbreakHelp.aspx
~/Frontend-Assembly/SitefinityWebApp/Mvc/Views/ExpertBio/DesignerView.Simple.ascx#OutbreakHelp.ascx
~/Frontend-Assembly/SitefinityWebApp/Mvc/Views/Shared/DesignerView.Simple.aspx#OutbreakHelp.aspx
~/Frontend-Assembly/SitefinityWebApp/Mvc/Views/Shared/DesignerView.Simple.ascx#OutbreakHelp.ascx
~/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Views/Designer/DesignerView.Simple.aspx#OutbreakHelp.aspx
~/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Views/Designer/DesignerView.Simple.ascx#OutbreakHelp.ascx
~/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Views/Shared/DesignerView.Simple.aspx#OutbreakHelp.aspx
~/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Views/Shared/DesignerView.Simple.ascx#OutbreakHelp.ascx
~/Views/Designer/DesignerView.Simple.cshtml
~/Views/Designer/DesignerView.Simple.vbhtml
~/Views/Shared/DesignerView.Simple.cshtml
~/Views/Shared/DesignerView.Simple.vbhtml
~/Frontend-Assembly/SitefinityWebApp/Mvc/Views/ExpertBio/DesignerView.Simple.cshtml#OutbreakHelp.cshtml
~/Frontend-Assembly/SitefinityWebApp/Mvc/Views/ExpertBio/DesignerView.Simple.vbhtml#OutbreakHelp.vbhtml
~/Frontend-Assembly/SitefinityWebApp/Mvc/Views/Shared/DesignerView.Simple.cshtml#OutbreakHelp.cshtml
~/Frontend-Assembly/SitefinityWebApp/Mvc/Views/Shared/DesignerView.Simple.vbhtml#OutbreakHelp.vbhtml
~/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Views/Designer/DesignerView.Simple.cshtml#OutbreakHelp.cshtml
~/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Views/Designer/DesignerView.Simple.vbhtml#OutbreakHelp.vbhtml
~/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Views/Shared/DesignerView.Simple.cshtml#OutbreakHelp.cshtml
~/Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Views/Shared/DesignerView.Simple.vbhtml#OutbreakHelp.vbhtml

**Comment by dzhenko** [comment]
Hey Steve,

You can find information about creating a new MVC widget [here](https://github.com/Sitefinity/feather/wiki/Create-a-%E2%80%9CHello-World%E2%80%9D-MVC-widget-in-a-separate-assembly) and about creating a custom designer view [here](https://github.com/Sitefinity/feather/wiki/Create-a-custom-designer-view) (as I see you already found).

Since I'm sure you red these articles, I suggest you share your widget with me, so I can inspect what's wrong and why the designer view can't be found. Just two quick reminders - If your widget is in separate assembly, all the views and scripts must be build as embedded resources and regardless of using a separate assembly or the SitefinityWebApp assembly, you must add the following attribute in your AssemblyInfo.cs:
```
[assembly: Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Controllers.Attributes.ControllerContainer] 
```

Kind Regards,
Dzhenko

**Comment by sitefinitysteve** [comment]
Support has the project if you want to ask them or get a copy?

It's a thunder generated MVC widget with no designer attached, so just living in the webapps MVC folder, no separate assembly.

**Comment by dzhenko** [comment]
Can you just confirm that placing the above-mentioned attribute in your AssemblyInfo.cs doesn't resolve this issue ?

**Comment by sitefinitysteve** [comment]
Ah that was it....weird I swear I've added that multiple times

Anyway, followup, designer loads in Advanced view by default, how do I set it to default to simple?

**Comment by dzhenko** [comment]
You need to add ~/Mvc/Views/[WidgetName]/DesignerView.[ViewName].json file that has content { "priority": 1 }. We will update our documentation to include this detail in the article. Meanwhile, you can find information about extending designers [here](https://github.com/Sitefinity/feather/wiki/Extend-widget-designer-with-additional-client-logic) (there is also a link in the article you read). 

If you have any more questions don't hesitate to contact us.

Kind Regards,
Dzhenko

**Comment by mariushm** [comment]
Hi Steve,

We created an article for enabling Feather in Thunder-generated widgets:
https://github.com/Sitefinity/feather/wiki/Enable-new-designers-in-widgets-created-with-Thunder

Thank you for bringing these up and keep developing with Feather. Let me know if you have other questions.

Mariush

**Comment by sitefinitysteve** [comment]
Thanks guys!
