### ISSUE TITLE
Widgets SemmanticUI with client validation always show error bubbles

### ISSUE THREAD

**Issue by Boyko-Karadzhov** [Sitefinity/feather#1337]
Widgets SemmanticUI with client validation always show error bubbles.

Make sure client validation is enabled on the project by adding these elements in appSettings in the web.config:

``` XML
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
```

Drag Profile widget on a page based on SemmanticUI template. You will see little red bubbles under the required inputs.

**Comment by ElenaGaneva** [comment]
We no longer provide support for SemmanticUI resource package so I am closing this issue.

Regards,
Elena
