### ISSUE TITLE
Search: No search results for undefined when sort search results on the frontend

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather#1340]
1. Create news item with name "news"
2. Create search index and reindex
3. Create a page with news widget
4. Create a page with search box
5. Create a page with search results and check "Allow users to sort results"
6. Navigate the page with search box on the frontend
7. Search for news
8. Order the results "Older first"

Result is: No search results for undefined

**Comment by ElenaGaneva** [comment]
Reproducible only in hybrid
