### ISSUE TITLE
Unable to edit a layout widget in 1.2.170.2

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#1351]
Chrome console shows an undefined error...and no layout editor shows up on the right pane.

![image](https://cloud.githubusercontent.com/assets/1542376/7209147/c7e8cc3a-e513-11e4-8819-3ddde9354377.png)

When I click the axd it says it's coming from Telerik.Sitefinity.Web.Scripts.LayoutEditor.js ...
}else{$(pane).imgAreaSelect(options);

...maybe the positioning of jQuery or something to "top"?  ...

Can it be replicated?

**Comment by dzhenko** [comment]
Hey Steve,

We currently do not support any editing of the layout widgets. All the alterations must be done trough the file system.

However, I tried to reproduce your issue and I was unable to do so. I will appreciate if you can give me some more context - which other scripts you use and how are you loading them or maybe the whole layout file. I see that you also use Kendo and I would like to know where and how you include it's scripts.

Kind Regards,
Dzhenko

**Comment by sitefinitysteve** [comment]
Well not *editing* in the sense that I could modify the column css (this has to be coming though I would imagine, it's impossible to have every combination with 12 sizes at 4 breakpoints plus offsets)

We've always been able to edit the feather layouts to add a wrapper class...so there much be something gimped with my project :/ 

...support has a copy

**Comment by mariushm** [comment]
You can work this around by not loading jQuery in the backend context. Use the following code to load jQuery in your layout file:
```C#
    @if (!SitefinityContext.IsBackend) 
    {
        @Html.Script(ScriptRef.JQuery, "top")
    }
```
