### ISSUE TITLE
Widget Template Editor: DynamicModule new fields not available

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#1400]
If I create a new field using the module builder, then go edit the razor template in the SF backend UI and reference that field, the widget throws a controller exception.  If I recycle the app pool on the server, the new field now works.

**Comment by mirinka** [comment]
Hi Steve, 
I created another field of short text to an existing dynamic module. Then I updated manually details template of my module and add code to display the new field. It works fine on my end without restart or recycle.
What type of widget template do you use - a custom one or the one that is shipped with feather? What type of field do you add to your dynamic module?

**Comment by sitefinitysteve** [comment]
Was a short text added in the module builder, then added to the detail template in the sitefinity UI...page was pure mvc feather.

Wierd, let me try to reproduce on a new project...
