### ISSUE TITLE
Content Block Html View: Problem if entering content in html view, then switching to Design View

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#141]
1. Open Feather Content Block - > Html View
2. Enter a content and switch to Design View
Note that many content block options are not visible any more, only dropdowns are available.
http://screencast.com/t/EMOmXYVArD0

**Comment by PetyaRachina** [comment]
not working only in Firefox now

**Comment by dzhenko** [comment]
Fixed in #131 branch
https://github.com/Sitefinity/feather/tree/editor-fullscreen-%23131

**Comment by Tihomir-Petrov** [comment]
Tested it in Chrome, IE11, Firefox 30, and Firefox 35.0. The fix is merged to master branch so QA engineer should check it directly there.
