### ISSUE TITLE
Blog Post:"OpenInSamePage" cannot be changed from Advanced settings

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather#1431]
1. Create a page
2. Drag and drop Blog post widget
3. Edit the widget
4. Switch to Advance settings
5. Set property "OpenInSamePage" to False
6. Save the widget
7. Edit the widget again and verify if the "OpenInSamePage" has value False

Actual result is: "OpenInSamePage" cannot be changed from Advanced settings

**Comment by ElenaGaneva** [comment]
In order for this to work you should set also DetailsPageId. This behavior is consistent for all list/detail widgets.

Regards,
Elena
