### ISSUE TITLE
Implement some sort of (optional) file version\date postfix to css\js

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#1464]
In webforms if you change the css file, it automatically applies a hash to the end so you never have to worry about telling users to clear their cache or remembering to manually do it in a layout\masterpage

Would love it if this made it's way to feather in some fashion

**Comment by GeorgiMateev** [comment]
Hi Steve,
I added an issue with the feature request in our backlog - https://github.com/Sitefinity/feather/issues/1532

In the meantime you can check this article http://www.codeproject.com/Articles/203288/Automatic-JS-CSS-versioning-to-update-browser-cach where is explained how this functionality can be implemented with a HttpFilter that is plugged in the Global.asax
