### ISSUE TITLE
CSS: Failed to load resource when delete selected css file

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather#1563]
1. Add Css widget to page
2. Edit widget and go to "Link to CSS file"
3. Press select button
4. Select css file
5. Save the widget and publish the page
6. Delete selected css file

Actual result is: On the frontend in browser console the following error:

Failed to load resource: the server responded with a status of 404 (Not Found)

P.S. Old widget displays: GET http://localhost:8010/test.css

**Comment by dzhenko** [comment]
Browser-specific and expected behavior.
