### ISSUE TITLE
JavaScript: Entering wrong url and pressing save is not allowed action and the error message appears for a second

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#1569]
1. Edit javascript widget, select Link to JavaScript file tab
2. Enter some invalid text in the URL field
Note that without changing the focus no error message appears
3. Press Save
Note that error message appears for just a second then the save action is performed, which is not correct

**Comment by manev** [comment]
No validation is required at all - Momchi
