### ISSUE TITLE
JavaScript: Problem when switching between the radio button options in IE

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#1589]
1. Open javascript widget for edit in IE
2. Switch to Link to JavaScript file option
3. Save the widget
4. Open the widget again for edit
5. Switch to Write JavaScript option
   Note that horizontal scroller appears and you are not able to see the cursor in the text area.
   You should start writing to fix the issue.

**Comment by ElenaGaneva** [comment]
This issue is not reproducible in 11.0+.
