### ISSUE TITLE
Language widget: Wrong behavior when changing the language from dropdown in page zone editor 

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#1618]
1. D&D language widget, edit it and select dropdown template
2. In page zone editor select different language
Note that a request for leaving the page is executed and you are asked to be redirected
In the old widget nothing happened. In my opinion in page zone editor this is the correct behavior.

**Comment by mirinka** [comment]
Verified for Dropdown template and Language links template
