### ISSUE TITLE
How to view previous version of documentation

### ISSUE THREAD

**Issue by rhullah** [Sitefinity/feather#1635]
I have a client that doesn't yet want to upgrade to v8.  Which means the new "reference scripts by component name" in the `DesignerView.[Name].json` file doesn't work in the version of Feather that I can use with this project.  Yet all the documentation has been update to the "component naming" style.  How can I see which scripts need to be used for a certain widget?

**Comment by PepiIvanova** [comment]
hi,

You can find details how to view documentation history in the following article:
https://help.github.com/articles/viewing-a-wiki-s-history-of-changes/

Best,
Pepi

**Comment by rhullah** [comment]
How do I know what version of a wiki page coordinates to which version of Feather?

**Comment by mariushm** [comment]
Hi Ryan,

Unfortunately, there's no convenient way to do this - the best we have at the moment is by comparing the datetime of the release tag and the document revisions. 
We are planning to move Feather documentation to the main Sitefinity doc portal, which support document versioning for the major versions. Do you think that would be enough or you also need versioning for the weekly Feather releases?

Mariush
