### ISSUE TITLE
Comments: Submit new comment on IE is not dispalyed

### ISSUE THREAD

**Issue by ElenaGaneva** [Sitefinity/feather#1660]
1)Enter comment on bootstrap page
Actual result : the comment is not visible in IE.

JS error occurs: SCRIPT438: Object doesn't support property or method 'format' 
on line 
239: newComment.find('[data-sf-role="comment-date"]').text(this.getDateFromSfString(comment.DateCreated).format(this.settings.commentDateTimeFormatString));

in comments-list.js

**Comment by Boyko-Karadzhov** [comment]
It's not about the browser. Make sure you don't have inline editing (don't be authenticated ) to reproduce the bug.
