### ISSUE TITLE
Server response times too slow with Project Feather

### ISSUE THREAD

**Issue by ckoch1979** [Sitefinity/feather#1676]
Please look at the thread at Google+!

https://plus.google.com/104320556709034419530/posts/VJ3yUFNzcR9

**Comment by mariushm** [comment]
Hi ckoch1979,

Thanks for alerting about this, we will look into this shortly and come up with needed optimizations.

Marush

**Comment by mariushm** [comment]
We have made some optimizations to the layout rendering in today's release, which should address the problem. Please upgrade to the latest nuget release and get back to us if you are still experiencing issues.
