### ISSUE TITLE
Template error after updating to version 1.2.200.1

### ISSUE THREAD

**Issue by StromKreis** [Sitefinity/feather#1679]
After updating to version 1.2.200.1 there are errors that the template can not be found .

![sf-error-admin](https://cloud.githubusercontent.com/assets/669412/7610723/622a8214-f97f-11e4-9a4a-0faa54a8ecf6.PNG)
![sf-error-page](https://cloud.githubusercontent.com/assets/669412/7610724/622c2c7c-f97f-11e4-9561-1b55bf036c13.PNG)

**Comment by mariushm** [comment]
Hi StromKreis,

This error occurs when the Grid widget you tried to drag does not belong to the package you page is based on. For example if your page is based on Foundation.default template, only the Foundation grid widgets will work. 
So please check the widgets you are using are from the same package and let me know if the problem persists. 

Mariush
