### ISSUE TITLE
Comments: Comments widget blinks in page zone editor

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather#1704]
1. Create a page (based on Bootstrap template) and one page on hybrid
2. Drag and drop Comments widget
3. Publish the page
4. Edit the page 

Actual result is: Comments widget blinks in page zone editor

Tha same behaviour if you add Comments widget on template (e.g Bootstrap) and hybrid

**Comment by VelinIV** [comment]
Loading bar appear when trying to edit the widget (only on page based on Bootstrap template)
http://screencast.com/t/vD8X4ZYJz
