### ISSUE TITLE
CSS widget: quotes ( "" ) are encoded

### ISSUE THREAD

**Issue by vbishurov** [Sitefinity/feather#1707]
1:) Create Pure MVC/Hybrid Page
2:) Place MVC CSS widget on the page
3:) Enter CSS with quotes e.g. 
body{
	background: url("");
}
4:) The quotes are encoded

**Comment by PepiIvanova** [comment]
Hi vbishurov,

Thanks for reporting this issue. I have added it as a bug to the Backlog.

Best,
Pepi
