### ISSUE TITLE
Site selector: Add "Other sites" option in Dropdown template

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#1723]
Add "Other sites" option in Dropdown template - this option is present in the old site selector widget when you have multisite enabled with 2 sites, and current site is not included.
OR
you have single site and current site is not included, then in new selector an empty dropdown appears, but in old site selector a dropdown with "Other sites" option appears

**Comment by PepiIvanova** [comment]
"Other sites" should be "-Select a site-" accordong to the wireframes http://ux.sitefinity.com/Sitefinity%20Feather/#p=site_selector
