### ISSUE TITLE
Grid controls in Layout Editor do not allow you to label layout elements

### ISSUE THREAD

**Issue by tmsimont** [Sitefinity/feather#1813]
When using the Feather grid controls in a page template editor you can't label the layout elements:

![Image of issue](http://i.imgur.com/AlvsBSc.png)

**Comment by PepiIvanova** [comment]
Hi,

I have added your request as an enhancement to the Backlog.

Thanks,
Pepi

**Comment by ElenaGaneva** [comment]
Hello tmsimont,

This functionality is added in the pop up window when choosing grid widget edit.

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
