### ISSUE TITLE
Kendo UI TreeView With Drag and Drop Functionality Breaks On Subsequent Loads of Widget Designer

### ISSUE THREAD

**Issue by MerrittMelker** [Sitefinity/feather#1814]
I am creating a custom widget designer view and on it there's nothing but a kendo ui tree view:

**DesignerView.TreeExample.cshtml**
```html
<div kendo-tree-view="tree"
     k-data-source="treeViewDataSource"
      k-options="treeOptions">
</div>
```
and **designerview-treeexample.js**
```javascript
(function ($) {
    var designerModule = angular.module('designer');

    designerModule.controller('TreeExampleCtrl', ['$scope', 'propertyService', function ($scope, propertyService) {
        $scope.feedback.showLoadingIndicator = true;
		
        $scope.treeData = new kendo.data.HierarchicalDataSource({
		   data: [
			   { text: "Item 1" },
			   {
				   text: "Item 2", items: [
				   { text: "SubItem 2.1" },
				   { text: "SubItem 2.2" }
				   ]
			   },
			   { text: "Item 3" }
		   ]
		});
		
		$scope.treeOptions = {
			dragAndDrop: true
		};

        //Makes call to the controlPropertyService to get the properties for the widgets.
        propertyService.get()
            .then(function (data) {
                if (data) {
                    $scope.properties = propertyService.toAssociativeArray(data.Items);
			   }
            },
            function (data) {
                $scope.feedback.showError = true;
                if (data)
                    $scope.feedback.errorMessage = data.Detail;
            })
            .finally(function () {
                $scope.feedback.showLoadingIndicator = false;
            });
    }]);
})(jQuery);
```

When you drop the associated widget on a page, then click on 'Edit', then select the view, the first time everything works correctly. Dragging and dropping is fine and functions properly. However, if you close the widget designer, by clicking 'Save', 'Cancel', or clicking the 'X' in the top right, then click the 'Edit' link again (and navigate to the correct view), the drag and drop functionality breaks. It starts posting javascript code in a string at the drop destination. Attached is a picture of me dragging the bottom most item in the tree to the top:

![merrittx1](https://cloud.githubusercontent.com/assets/11414229/7786595/0726a172-019f-11e5-80d9-cd56d0229a27.png)

**Comment by PepiIvanova** [comment]
Hi,

I have modified your code a little bit to make it working:
- wrap kendo tree with ng-controller:
```html
<div ng-controller="TreeExampleCtrl">
    <div kendo-tree-view="tree"
            k-data-source="treeData"
            k-options="treeOptions">
    </div>    
</div>
```
- push kendo.directives to designer module
```javascript
(function ($) {
    var designerModule = angular.module('designer');
    designerModule.requires.push('kendo.directives');

    designerModule.controller('TreeExampleCtrl', ['$scope', 'propertyService', function ($scope, propertyService) {
        $scope.feedback.showLoadingIndicator = true;

        $scope.treeData = new kendo.data.HierarchicalDataSource({
        ...
```

After the changes the designer started to load properly but I cannot reproduce the described issue. Do  you have something else in the designer except the tree view? 

Best,
Pepi

**Comment by MerrittMelker** [comment]
I can't confirm that it's working but I moved onto using hierarchical kendo grids with my own home grown custom directive for achieving a similar functionality.
