### ISSUE TITLE
Feature request: Show exception details if a runtime error occurs in a widget's view.

### ISSUE THREAD

**Issue by kyleballard** [Sitefinity/feather#182]
If a widget view throws an error, it would be helpful to see this error if customErrors are turned off in web.config.   An example is that a view may not have the model type properly defined that the controller is passing to it.  Simiarly, razor syntax may produce an error as well.

Current Sitefinity behavior, as far as I can tell, as of version 7.3, appears to be to swallow the error and not display the widget view.   Also as far as I can tell, no logging is occuring showing that this view was not rendered for X reason/exception.

This would be very useful to help with troubleshooting.   As it stands, trial and error is the only solution for dealing with this.

**Comment by mariushm** [comment]
Hi Kyle,

We have implemented this in 1.1.40, which was released last Friday:
https://github.com/Sitefinity/feather/wiki/Display-error-message-when-exception-occurs

To benefit from this, please upgrade to [Feather 1.1.40](https://github.com/Sitefinity/feather/wiki/upgrade-instructions) via a Nuget package.

**Comment by anibarro** [comment]
It seems to be broken again as of Feather 1.1.70.1

**Comment by mariushm** [comment]
Hi Ani,

We tested it with 1.1.70.1 and it worked as expected - when customErrors=**Off** and exception occurs, a message is informing you to check the logs.
Please try again and share more details about your case if it still doesn't work for you.

**Comment by pmedina** [comment]
Doesnt work for me. Custom errors are set to off and a buggy controller swallows the exception so it cant be blamed :)

**Comment by anibarro** [comment]
Hello mariushm,

Please take a look at this screencast showing the issue: 
http://screencast.com/t/vp6Lgxe4Qc
