### ISSUE TITLE
Server Error when enabling CDN

### ISSUE THREAD

**Issue by ckoch1979** [Sitefinity/feather#1825]
I enabled CDN in script manager. Now I am getting the attached error when I am logged in the backend and browsing the frontend. This only happens if I use a template with Feather.

If I delete the following lines from default.cshtml (Bootstrap), the error does not occur.

  @if (!SitefinityContext.IsBackend
          && ControlExtensions.InlineEditingIsEnabled()
          && !SystemManager.CurrentHttpContext.Request.IsAjaxRequest())
    {
     @Html.Script(ScriptRef.MicrosoftAjax, "top")
    @Html.Script(ScriptRef.MicrosoftAjaxCore, "top")

    @Html.Script(ScriptRef.JQuery, "top")
      @Html.Script(Url.EmbeddedResource("Telerik.Sitefinity.Resources.Reference", "Telerik.Sitefinity.Resources.Scripts.jquery.ba-outside-events.min.js"), "top")
      @Html.Script(ScriptRef.KendoAll, "top")
      @Html.Script(Url.EmbeddedResource("Telerik.Sitefinity.Resources.Reference", "Telerik.Sitefinity.Resources.Scripts.RequireJS.require.min.js"), "top")
      @Html.InlineEditingManager(false)
    }

![cdn](https://cloud.githubusercontent.com/assets/12174524/7808706/75cf9b54-0395-11e5-9005-66946fac4268.PNG)

**Comment by PepiIvanova** [comment]
Hi,

Thanks a lot for reporting this issue. I have logged it as a bug in the Backlog.

Best,
Pepi

**Comment by mariushm** [comment]
Hi ckoch1979,

The issue was resolved in the latest release, you can now use CDN for the scripts.

Mariush
