### ISSUE TITLE
Selectors templates contains class='modal-body'

### ISSUE THREAD

**Issue by NadezhdaPetrova** [Sitefinity/feather#183]
News/Page/DynamicContntent/etc. selectors tempaltes contain <div class='modal-body'>. This causes some issues in the link selector: there are two nested <div class='modal-body'>. The UX team workaround this. This div must be moved to sf-list-selector.html. 

NOTE: when fixed, talk to UX team

**Comment by KirilVandov** [comment]
This is resolved in the latest version of 11.0 + (http://nuget.sitefinity.com/#/package/Telerik.Sitefinity.Feather.Core)
