### ISSUE TITLE
Login / Logout button - wrong redirect on logout when SSL is used

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#1838]
Steps to reproduce:
1. setup Sitefinity site with SSL, e.g. https://www.mysite.com
2. create a page with Login / Logout button widget, e.g. statuspage
3. setup Login / Logout button and set "After logout users will be redirected to..." to a page, e.g. mypage
4. view statuspage on frontend and logout
As a result: wrong redirect to https://www.mysite.com/m/mypage

Note that "m/" is added in URL and "m" is the last symbol of https://www.mysite.com
If your url is ending in .tv or .bg, then you will be redirected to:
https://www.mysite.com/v/mypage or
https://www.mysite.com/g/mypage

**Comment by manev** [comment]
Thre is a bug in Sitefinity which leads to this problem
The workaround is to add extra slash at the end of realm parameter in the web.config file:
https://www.mysite.com should be: https://www.mysite.com/
