### ISSUE TITLE
Categories: sample how to display hierarchical categories tree in the frontend

### ISSUE THREAD

**Issue by GeorgiMateev** [Sitefinity/feather#1860]
The categories model has ability to return tree of categores. Only a view where the tree is displayed should be added.

**Comment by GeorgiMateev** [comment]
This is the article https://github.com/Sitefinity/feather-docs/wiki/Add-view-with-categories-tree-in-the-Categories-widget

**Comment by ElenaGaneva** [comment]
https://docs.sitefinity.com/add-hierarchical-tree-view-in-the-categories-widget-mvc
