### ISSUE TITLE
Comments: error when comments widget is dragged and dropped on Bootstrap, Semantic and Foundation templates

### ISSUE THREAD

**Issue by ghost** [Sitefinity/feather#1861]
1. Go to Design->Page Templates and select Bootstrap Semantic or Foundation template
2. Drag and drop Comments widget and publish
3. Select again the template and check the console for errors

Actual result:
Error appears in the console
GET http://localhost:8088/RestApi/comments-api/comments/count?ThreadKey=&_=1432897058201 400 (ArgumentException)
GET http://localhost:8088/RestApi/comments-api/comments/?ThreadKey=&Take=50&SortDescending=True&_=1432897058202 400 (ArgumentException)
GET http://localhost:8088/RestApi/comments-api/notifications/?threadKey=&_=1432897058203 400 (ArgumentException)

**Comment by ElenaGaneva** [comment]
This is only reproducible if you drag the widget while the comments for page are not allowed
