### ISSUE TITLE
Including Script Reference to Angular on a Widget View: 

### ISSUE THREAD

**Issue by MerrittMelker** [Sitefinity/feather#1870]
Top of my widget view basically looks like this:

```html
@Html.Script(ScriptRef.JQuery, "top", false)
@Html.Script("http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-rc.2/angular.min.js", "top")
@Html.Script("http://ajax.googleapis.com/ajax/libs/angularjs/1.4.0-rc.2/angular-resource.min.js", "top")
@Html.Script(Url.WidgetContent("~/Mvc/Scripts/Production/app.js"), "top")
@Html.Script(Url.WidgetContent("~/Mvc/Scripts/Production/controllers.js"), "top")
@Html.Script(Url.WidgetContent("~/Mvc/Scripts/Production/services.js"), "top")
```
When editing a page containing this widget, when i first load the page editor the console (in chrome) warns about loading angular twice:

> WARNING: Tried to load angular more than once.

I looked at the sources and sure enough your loading angular as well on this page:

> Frontend-Assembly/Telerik.Sitefinity.Frontent/Mvc/Scripts/Angular/angular.min.js

Anyways, how can I avoid getting this error message. On a related note, the first time I drop this same widget onto a container (on the page) the data binding of my model doesn't seem to work and the angular code doesn't seem to be run at all, well according to my console logging:

![untitled screencast 1](https://cloud.githubusercontent.com/assets/11414229/7895180/97cb363a-0644-11e5-9254-ee2feb8365d1.gif)

However, no errors are shown in the console. If I save the page, then come back to it, the angular looks as if it hasn't ben run intially, but then suddenly the page flashes and bam! there's the proper angular processed html.

![untitled screencast](https://cloud.githubusercontent.com/assets/11414229/7895173/2770116c-0644-11e5-8565-c6f3244d47fc.gif)

The breakpoint hit is within the controller:

```javascript
"use strict";

/* Controllers */

var indexControllers = angular.module("indexControllers", []);

indexControllers.controller("indexCtrl", [
    "$scope", "indexServices", function ($scope, indexServices) {

        angular.element(document).ready(function () {
            debugger;
            $scope.productions = indexServices.query({ taxonomyGuid: $scope.selectedParentFilterId, taxonGuid: $scope.selectedFilterId });
        });

        $scope.onFilterClick = function (title, taxonomyGuid, taxonGuid) {
            $scope.selectedFilterId = taxonGuid;
            $scope.currentFilter = title;
            $scope.selectedParentFilterId = taxonomyGuid;
            indexServices.query({ taxonomyGuid: taxonomyGuid, taxonGuid: taxonGuid },
                function(data) {
                    $scope.productions = data;
                },
                function(response) {
                    alert(response);
                });
        };
    }
]);
```

**Comment by Boyko-Karadzhov** [comment]
Hello Merritt,

Scripts are not ran when widgets are being dragged and dropped from the toolbox. That is why at first you don't see any data binding.

We use angular for the designers and that is why we have it loaded. Since you are loading it from a different source it is loaded twice. 

In order to display meaningful content in design mode and avoid double loading you can have something like this:

```cshtml
   @Html.Script(Url.WidgetContent("Mvc/Scripts/Angular/angular.min.js"), "top")
   @Html.Script(Url.WidgetContent("Mvc/Scripts/Angular/angular-resource.min.js"), "top")
   [Some other references]

   @if (SystemManager.IsDesignMode)
   {
      [Static content that represents the widget's purpose and layout]
   }
   else
   {
      [Angular bound stuff.]
   }
```

Regards,
Boyko
