### ISSUE TITLE
Image gallery widget is missing in documentation

### ISSUE THREAD

**Issue by ckoch1979** [Sitefinity/feather#1871]
Can not find the documentation for the image gallery widget here: https://github.com/Sitefinity/feather/wiki

**Comment by ElenaGaneva** [comment]
Hello ckoch1979,

Thank you for reporting this to us. I am adding this in our backlog.

Regards,
Elena

**Comment by PepiIvanova** [comment]
Hello ckoch1979,

You can find the documentation for Image gallery widget here: https://github.com/Sitefinity/feather/wiki/MVC-Image-gallery-widget

Best,
Pepi
