### ISSUE TITLE
Feather Content block: full screen for HTML view does not expand window properly

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#188]
Branch: master
Steps to reproduce:
1. create page
2. drag and drop Content block
3. open designer
4. switch to HTML view
5. click Toggle button
As a result: window is not fully expanded (see screenshot)
![image](https://cloud.githubusercontent.com/assets/234207/5874631/a8ca12d0-a30c-11e4-8623-ba7fcbae9244.png)

**Comment by dzhenko** [comment]
html-editor-fullscreen-toggle-#189
