### ISSUE TITLE
Feather Content block: Multilingual - default language title is displayed in language selector for all languages

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#190]
Branch: master
Pre: Multilingual is enabled - EN default, DE, BG languages
you have test page with translation in all languages ("test en" for EN, "test de" for DE and "test bg" for BG)
Steps to reproduce:
1. create page
2. drag and drop Content block widget
3. open designer
4. open link selector
5. switch to "Page from this site"
6. select English language -> "test en" appears in page selector
7. select German language -> "test en" appears in page selector instead of "test de"
8. select Bulgarian language -> "test en" appears in page selector instead of "test bg"
NOTE: it work fine in old link selector
related to #225 Link selector - Page from this site: search in Multilingual results in pages from default language only

**Comment by PetyaRachina** [comment]
The page should be translated in all languages in order to reproduce it
