### ISSUE TITLE
Revision history not working with pages using feather based template

### ISSUE THREAD

**Issue by Sschlenker** [Sitefinity/feather#1927]
I have a custom package that I did a full copy from the Bootstrap version on.  I then made base a page based on the template.

When I first open revision history up I see all the versions and the status as to what is currently published and etc.  When I click on a version to view what it looked like I am presented with a blank page other than the toolbar at the top.

I am seeing a lot of errors like this in my log:
 Cannot find template "~/Frontend-Assembly/Telerik.Sitefinity.Frontend/GridSystem/Templates/template-content.html".

That layout exists in the custom package that I have created and renders fine on pages, but seems to be causing issues in revision history.

Full stack from error log:

Type : System.ArgumentException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Message : Cannot find template "~/Frontend-Assembly/Telerik.Sitefinity.Frontend/GridSystem/Templates/template-content.html".
Source : Telerik.Sitefinity.Frontend
Help link : 
ParamName : 
Data : System.Collections.ListDictionaryInternal
TargetSite : System.Web.UI.ITemplate GetTemplate(Boolean, Boolean, System.String)
HResult : -2147024809
Stack Trace :    at Telerik.Sitefinity.Frontend.GridSystem.GridControl.GetTemplate(Boolean isVirtualPath, Boolean isHtmlTemplate, String layout)
   at Telerik.Sitefinity.Frontend.GridSystem.GridControl.GetTemplate()
   at Telerik.Sitefinity.Web.UI.LayoutControl.Initialize()
   at Telerik.Sitefinity.Web.UI.LayoutControl.CreateChildControls()

Additional Info:

TimeStamp : 6/2/2015 8:13:08 PM
FullName : Telerik.Sitefinity.Utilities, Version=8.0.5710.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
AppDomainName : /LM/W3SVC/3/ROOT-2-130777494462354968
ThreadIdentity : admin

Requested URL : http://localhost:60876/Sitefinity/Versioning/4906bdfd-f51b-6204-97bc-ff00001db1ce/c90fbdfd-f51b-6204-97bc-ff00001db1ce?IsTemplate=false&uiCulture=

**Comment by ElenaGaneva** [comment]
Hello Sschlenker,

Thank you for reporting this issue. We are currently working on it and we will try to include it in one of the upcoming releases. We will update you as soon as the fix is available.

Regards,
Elena
