### ISSUE TITLE
Login Form - Dynamic redirection after login

### ISSUE THREAD

**Issue by Sylvain-S** [Sitefinity/feather#1932]
Steps to reproduce:

- Create page "A" with login/logout button
- Create page "Login" with login form
- Try the login process coming from page A. If you don't specify any page in the property "After login users will be redirected to...", you stay on the login page.

In this case, default behaviour should be a redirection to page A (logged in).( Maybe a additional option in the widget may be added )

**Comment by ElenaGaneva** [comment]
Hello Sylvain-S,

Would you provide me with some additional details:
* Is any of the mentioned pages home page for your site?
* Are you using multisite? Is this scenario reproducible in your default site?

Thanks in advance.

Regards,
Elena

**Comment by Sylvain-S** [comment]
Hello Elena,

1) Not necesseraly, the redirection should occur at any time( regardless of the page, excepted if the page is not allowed to logged in users).

2) Yes, and I have the same behaviour for the default site (I stay on the login page instead of being redirected)

Thanks to you,
Sylvain

**Comment by ElenaGaneva** [comment]
Thank you for reporting this issue and providing the details. I am adding it to the backlog so we can investigate it further.

Regards,
Elena
