### ISSUE TITLE
Using Feather layout template in a Page and setting it for authenticated users only throws an error when access it.

### ISSUE THREAD

**Issue by svetoslav-manchev** [Sitefinity/feather#194]
Steps to reproduce:
- Create a Page based on Build-in feather template (for example Bootstrap)
- Set this page permissions (Action > Permissions > View (Authenticated users only)
- Publish the Page and View
  After input the credentials the error is thrown. 

Temporary workaround:
- Go to: ~/ResourcePackages/<your template>/MVC/Views/Layouts/
- Open the file Default.cshtml
- Remove (or comment) the following line: @Html.InlineEditingManager(false)

**Comment by KirilVandov** [comment]
This is resolved in the latest version of 11.0 + (http://nuget.sitefinity.com/#/package/Telerik.Sitefinity.Feather.Core)
