### ISSUE TITLE
Can't define a script to load in a section unless it appears after the section definition

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#1947]
Works:   
 @Html.Section("bottom")
    @Html.Script(ScriptRef.JQuery, "bottom")

Fails:
    @Html.Section("top")
    @Html.Script(ScriptRef.JQuery, "bottom")
.....
    @Html.Section("bottom")

**Comment by dzhenko** [comment]
Hey Steve,

The __Html.Section__ is designed to be used in layout files. It serves a similar role as the ASP.NET MVC __RenderSection__ method. Therefore using it in the same place as a __Html.Script__ or __Html.StyleSheet__ will work only if you take care of the ordering as described in your issue. 

An easy workaround is to move the __Html.Script__ or __Html.StyleSheet__ methods on the lines that you want to render them - without having to use the __RenderSection__ method at all. Another solution is to just use the default sections that come with the default resource layout - "top","bottom" and "head". You can see more information [here](https://github.com/Sitefinity/feather-docs/wiki/Refer-to-resources-inside-MVC-views).

We also recommend avoiding creation of sections with the names "top","bottom" and "head", as they are used by the default widgets that ship with Feather.

Kind Regards,
Dzhenko

**Comment by JohnAbassian** [comment]
>The Html.Section is designed to be used in layout files. It serves a similar role as the ASP.NET MVC RenderSection method. 

Any reason we can only use it with Script and Stylesheet? With the MVC RenderSection method, I can put anything in the section, for example, meta tags. 

Are my only options to use javascript to modify the head, or to create my own helper?
