### ISSUE TITLE
Question about ~Mvc/Views/Layouts/*

### ISSUE THREAD

**Issue by tmsimont** [Sitefinity/feather#1956]
Is there a model that we can use in the cshtml files that are used for Layouts?

For example, I have ~/Mvc/Views/Layouts/base.cshtml

I want to identify the homepage in this template. I figured I can add a custom field to the pages and then try to use that in the template.

There is no `@model` declaration in any of the Layouts I can find.

What type is the `@model` passed to the Views in /Layouts/ that are used for templates?

How can I identify the homepage in these files?

**Comment by PepiIvanova** [comment]
Hi tmsimont ,

Currently there is no way to pass the model to Layouts. If you want just to display homepage you can implement a helper method that will get the home page for the current site and use it in the layout file:

```
public static MvcHtmlString RenderHomePage(this HtmlHelper helper)
        {
            var homePageId = SystemManager.CurrentContext.CurrentSite.HomePageId;
            var siteMap = Telerik.Sitefinity.Web.SitefinitySiteMap.GetCurrentProvider();

            SiteMapNode node;
            var sitefinitySiteMap = siteMap as Telerik.Sitefinity.Web.SiteMapBase;
            if (sitefinitySiteMap != null)
            {
                node = sitefinitySiteMap.FindSiteMapNodeFromKey(homePageId.ToString(), false);
            }
            else
            {
                node = siteMap.FindSiteMapNodeFromKey(homePageId.ToString());
            }

            return new MvcHtmlString(node.Title);
        }
```

```html
...
<strong>@Html.RenderHomePage()</strong>
<div class="sfPublicWrapper" id="PublicWrapper">
      @Html.SfPlaceHolder("Contentplaceholder1")
</div>
...
```

Let us know if this helps,
Pepi

**Comment by tmsimont** [comment]
Thanks Pepi,

That is helpful.

However, what I'm trying to do is create a variable that identifies if the template is being used on the homepage, which would be useful for adding scripts or body classes to the homepage only, without requiring usage of a different file for the homepage.

I tried something like this:

```
@helper GetBodyClass() {

	var site = SystemManager.CurrentContext.CurrentSite;
	var homePageId = site.HomePageId;

	SiteMapNode currentNode = SiteMapBase.GetCurrentProvider().CurrentNode;
	PageSiteNode node = (PageSiteNode)currentNode;
	
	//todo: why doesn't this work? the GUID is off by 1 bit... related to translations?
	if (node.PageId.Equals(homePageId))
	{
		@Html.Raw("homepage");
	}
	else
	{
		@Html.Raw("innerpage");
	}
}
```

It almost works, but for some reason `node.PageId` is 1 bit off from `homePageId`
I'm not sure why that would be...

**Comment by PepiIvanova** [comment]
Hi tmsimont,

You can use following code to check if the current node is a home page or not:

```
var currentNode = SiteMapBase.GetActualCurrentNode();
            if (currentNode != null)
            {
                if (currentNode.IsHomePage())
                    @Html.Raw("homepage");
                else
                    @Html.Raw("innerpage");
            }
```

Hope this helps,
Pepi

**Comment by tmsimont** [comment]
Hi Pepi,

Unfortunately this does not work. I imagine that this does something similar to the code I posted, but for some reason the GUID of the "currentNode" is just 1 bit off from the GUID of the homepage node. I suspect this has something to do with there being multiple languages on the site. In any case, it does not work.

**Comment by tmsimont** [comment]
Oh nevermind it worked! The old code I had must have been cached
