### ISSUE TITLE
Search Results: Results are not sorted

### ISSUE THREAD

**Issue by veliniv** [Sitefinity/feather#1963]
1. Create a page with Search Box widget
   and select search index
2. Create a page and drop Search Results widget and check Allow users to sort results
3. Create some pages, drop Content block widget and add some text 
4. Make a search and try to sort the results

Actual result:
The results are not sorted
Does not apply for other items except pages

**Comment by dzhenko** [comment]
This seems to be a issue with Lucene - the query is properly built and passed to the Lucene search service. Should resolve after upgrading Lucene.

**Comment by RJCuthbertson** [comment]
@dzhenko has Lucene been upgraded? And did that resolve this issue? I'm wondering if we can close this.

**Comment by ElenaGaneva** [comment]
Hello,

This issue has been fixed in [version 11.1](https://github.com/Sitefinity/feather/releases/tag/v.11.1.6800.0) of Sitefinity.

Regards,
Elena
