### ISSUE TITLE
Link Selector: Edit a link which is an images is not navigate to the correct option and selector is empty

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#198]
1. Open content block with an image, select it and make a link with Pages, Anchor or Email option
2. Insert link, Save content block
3. Open content block widget for edit, select the image and open link selector
Note that you are navigated to the web address option, and no information is persisted for this image in the selector

**Comment by PepiIvanova** [comment]
cannot reproduce
