### ISSUE TITLE
Content block: add space in Strike tooltip

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#1986]
Tooltip should be "Strike through"

![image](https://cloud.githubusercontent.com/assets/234207/8082066/f81a4fe8-0f82-11e5-9fda-5eb95fa4d8a1.png)

**Comment by JenPeleva** [comment]
This tooltip comes from the default tools of the editor - same in the demo.
http://demos.telerik.com/kendo-ui/editor/all-tools
