### ISSUE TITLE
Feather widgets: Widgets display incorrect information in widget designers, when they are edited on page 

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather#2000]
1. On template Bootstrap template drag and drop Image widget and select an image
2. Make widget "Editable on pages", publish template
3. Create new page, using Bootstrap template
4. Edit the image widget, select a different image and save
5. Edit the widget - although the widget shows your new image, the edit dialog shows your old image.

See attached screen: http://screencast.com/t/Gfze9a8wio 
------
The issue is reproducible for all widgets:

0. Create two news items
1. Drag and drop widget on page template (e.g. bootstrap template) - e.g News widget and select news item
2. Make widget editable on page
3. Create a page based on this template
4. Edit the page and edit the widget 
5. Change something in the widget (change the selected news item)
6. Save changes and edit the widget again
7. Check what is saved 

Actual result is: The changes are not saved in the widget designer and the selecte dnews item is not correct, but the widget displays correct information in page zone editor and on the frontend

**Comment by Stephen2** [comment]
Hi Sitefinity, please note I submitted this bug and it is mis-titled.  The problem doesn't lie in the image widget, as multiple (all?) MVC widgets exhibit this same behaviour, including custom widgets.

**Comment by NadezhdaPetrova** [comment]
NOTE: The selected Id is populated correctly on the server. But propertyService returns the old Id.

**Comment by Stephen2** [comment]
Hopefully it can make it for the next milestone!  Good luck everyone
