### ISSUE TITLE
Widget Details view for Products not working

### ISSUE THREAD

**Issue by rhullah** [Sitefinity/feather#2009]
Starting from Feather v1.2.140.2, the [details view of a widget](https://github.com/Sitefinity/feather/wiki/How-to-implement-a-Master-Detail-content-controller) doesn't work if the item is a Product.

**Comment by dzhenko** [comment]
Hi rhullah,

Thanks for reporting this issue. We will try to fix it and include it in our next release.

Kind Regards,
Dzhenko

**Comment by mariushm** [comment]
Hi,

The fix was shipped with Feather 1.2.260.1

Mariush
