### ISSUE TITLE
How to use Details view for custom Taxonomy?

### ISSUE THREAD

**Issue by rhullah** [Sitefinity/feather#2010]
I've seen the wiki page about [how to implement actions that filters by category or tag](https://github.com/Sitefinity/feather/wiki/How-to-implement-action-that-filters-by-category-or-tag), but that only seems to work with the Category and/or Tag taxonomies.  I can't get it to work on a custom taxonomy.  I would prefer my Url structure to be like the following:

    ~/page/{taxon-url-name}

I can I go about achieving this capability?

**Comment by dzhenko** [comment]
Hi rhullah,

Currently you are unable to use the built-in "ListByTaxon" route with custom taxonomy. This is part of the routing story that we are currently developing with high priority and we hope to finish in the nearest future.

Kind Regards,
Dzhenko

**Comment by rhullah** [comment]
Was this closed because it was implemented?

**Comment by rhullah** [comment]
@dzhenko What's the status of this?  Is this now doable?

**Comment by dzhenko** [comment]
Hi rhullah,

We have this issue in our backlog and we will contact you when we make progress.

Kind Regards,
Dzhenko
