### ISSUE TITLE
Kendo UI editor is wrapping text in <span> with inline styles for color, line-height

### ISSUE THREAD

**Issue by tmsimont** [Sitefinity/feather#2015]
It seems that the issue may be because of the way Foundation and Bootstrap apply text styles directly to the body element.

This thread seems to indicate that this causes the editor to wrap text in <span> with inline styles:
http://www.telerik.com/forums/radeditor-adds-span-tags-around-text

Is there any way to alter ~/client-components/fields/html-filed/sf-html-field.sf-cshtml so the kendo editor does not try to wrap content with span tags?

As an example, this is what I get in the HTML generated by the editor, simply by typing into the editor:

```
<span style="font-family:inherit;font-size:1rem;color:#4d4d4f;">Quis pecus cui antehabeo abluo transverbero luptatum quidne foras praesent consequat obruo.</span>
```

Inserting inline color styles makes it impossible to use CSS to style content.

**Comment by dzhenko** [comment]
Hi tmsimont,

Unfortunately there is no way to change this behavior of the kendo editor - this is how it is implemented to work. You can check [this thread](http://www.sitefinity.com/developer-network/forums/bugs-issues-/html-editor-adds-span-tag-with-line-height) for a similar issue.

I would suggest adding some custom javascript to remove all style attributes from all the child elements of the rendered widget content. For example something like 

``
     $('.contentBlock').find("*").removeAttr('style') 
``

can be used to remove all the inline styling done by the kendo editor (given that the content block has this 'contentBlock' class). Please note this solution may have unwanted side effects.

Kind Regards,
Dzhenko
