### ISSUE TITLE
Navigation item doesnt show in menu if used as redirect or group

### ISSUE THREAD

**Issue by elivnjak** [Sitefinity/feather#2019]
1. Select show in navigation
2. This page redirects to another page OR Use this page only to group other pages

That page doesnt show in the navigation. I saw previous issues with a closed status but not sure if its exactly the same issue.

Cheers,
Edin

**Comment by ElenaGaneva** [comment]
Hello Edin,

I have been testing the issue that you mentioned and I was not able to reproduce it. Would you provide me with some details on the matter:

- Which version of Sitefinity do you use? (for example 8.0.5700.0)
- Which version of Feather do you use? (for example 1.2.250)
- Do you place the navigation on hybrid page or do you use template (like Bootstrap)?
- Do you make any additional configuration over the widget (for example did you change the values for *Display*, *Levels to include*, *Template* sections of the designer when configuring the widget)?

Thanks in advance.

Regards,
Elena

**Comment by elivnjak** [comment]
Hi Elena,


Thanks for looking into it.

  *   Which version of Sitefinity do you use? (for example 8.0.5700.0) - 8.0.5700.0
  *   Which version of Feather do you use? (for example 1.2.250) - 1.2.130.0
  *   Do you place the navigation on hybrid page or do you use template (like Bootstrap)? - I use a custom MVC Template.
  *   Do you make any additional configuration over the widget (for example did you change the values for Display, Levels to include, Template sections of the designer when configuring the widget)? - No. Using standard settings.

Kind Regards,
Edin


________________________________

**Comment by ElenaGaneva** [comment]
Hi Edin,

Thank you for the details. I tested the widget with the versions that you specified and I am still not able to reproduce the issue – on my side both group and redirect pages were displayed in the Feather Navigation. 

Would you please make sure to set *Levels to include* setting of the widget to *All* from widget’s designer. The default setting is 1, therefore only pages that you have on first level will be displayed when dropping the widget. 

Regards,
Elena
