### ISSUE TITLE
Subscribe Form: Exception appears on frontend if you choose "Open a specially prepared page...", but selecting no page

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#2025]
1. Open Subscribe form for edit 
2. Choose "Open a specially prepared page..."
3. Do not select any page, Save
4. Publish the widget
5. Enter an email on frontend and Subscribe
Note than an exception appears

**Comment by PepiIvanova** [comment]
In this case we will automatically select "Show message" option

**Comment by SlaveyaShtereva** [comment]
If you select a page. then delete this page, the problem is still reproducible

**Comment by PepiIvanova** [comment]
In case page is deleted, we will display the successful unsubscribe message.
