### ISSUE TITLE
Subscribe Form: A successful green messege should appear after entering correct or existing email

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#2028]
1. D&D subscribe form widget
2. On frontend enter correct email address or existing email address
Note that a green successful message should appear in both cases on the same page as the subscribe form widget:
http://screencast.com/t/Yer8XusNc5

**Comment by NadezhdaPetrova** [comment]
The same thing applies for the subscribe link in Unsubscribe widget.
