### ISSUE TITLE
Content block: issues when you resize the window in fullscreen

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#203]
1. Create a page
2. Drag and drop a content block widget
3. Edit the widget
4. Switch to full screen mode
5. Resize the browser window - as a result: some buttons are hidden instead of responsively aligned - http://screencast.com/t/UHodNsbpr

**Comment by KirilVandov** [comment]
This is resolved in the latest version of 11.0 + (http://nuget.sitefinity.com/#/package/Telerik.Sitefinity.Feather.Core)
