### ISSUE TITLE
Subscribe/Unsubscribe: If email campaign module is not licensed, designers should show error

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#2046]
1. Create a license with no email campaign module licensed
2. D&D subscribe form widget ( or unsubscribe widget )
Note that in page zone editor there is no error message, telling that the module is not licensed
3. Press Edit
Note that again there is no error message
4. Select mailing list and save
Note that now there is an error message.
Error messages should be shown after D&D and after Edit widget, not when mailing list is selected and widget is saved

**Comment by PepiIvanova** [comment]
The case when D&D widget is fixed.
