### ISSUE TITLE
Is it possible to include a folder under each framework that has each of the css files split out

### ISSUE THREAD

**Issue by ahazelwood** [Sitefinity/feather#2051]
While it is nice to have a single css file for all styles within each framework available to get started, it makes it hard to update individual parts on their own, or to include additional libraries when one is creating a new resource.  With tools like Web Essentials able to create a css bundles file, this becomes easy to perform the minification within visual studio.  I'm not suggesting you replace how you are currently building the combined css file, just that there is another source directory that includes each individual css file separately.  

For example, under the Bootstrap/assets/dist/css folder there is one styles.css file.  I would love to see an additional folder somewhere that breaks out bootstrap from this file into it's own bootstrap.css file, glyphicons, html5 boilerplate, etc.  Then potentially, even a css bundle file in this directory that builds the styles.css file would be the perfect addition.  This makes it easy then to add my own css files into the mix and have them combined and minified at build time.

Let me know if any additional clarification would help on this request.

As a long-time user of Sitefinity, I'm excited by the progress of the feather project and look forward to using it soon for our main website.

Thanks.

**Comment by ElenaGaneva** [comment]
Hi ahazelwood,

Thank you for your suggestions. Actually currently we have grunt task which builds the mentioned styles.min.css file when you edit some of the separate sass files. I can suggest you check the following forum thread which we discuss approaches for customizing/adding new styles for a package:   

https://github.com/Sitefinity/feather-packages/issues/119 

If you have any additional suggestions or if you require more details on the matter please do not hesitate to contact us.

Regards,
Elena
