### ISSUE TITLE
Social share buttons to single news item

### ISSUE THREAD

**Issue by Masahigo** [Sitefinity/feather#2058]
Hi,

I noticed this feature to "Enable social share buttons" under News widget designer's Single Item Settings tab is missing from the Feather's News widget

![enable social share buttons checkbox in news widget old widget designer](https://cloud.githubusercontent.com/assets/9364649/8283030/4cb03fa8-18fd-11e5-98ff-9dd86d5f6f1d.jpg)

![enable social share buttons checkbox in news widget new widget designer](https://cloud.githubusercontent.com/assets/9364649/8283027/3b8bd746-18fd-11e5-880f-58cdcc5745b7.jpg)

This feature would be very valuable to us since otherwise we have to create a separate page for the news items detail view and place the social sharing buttons there using the Social share widget. This is not desired because it results to extra pages in the site structure and search engines depreciate it as well.

It would also be good if this template for the social sharing buttons in single news items would be freely editable from under the ResourcePackage.

**Comment by PepiIvanova** [comment]
Hi Masahigo,

You can find EnableSocialSharing property under News widget Advanced settings > Model. To enable users to share your content in Facebook, Google+, Twitter, and so on, set the value of this property to True. By default, the value is False (https://github.com/Sitefinity/feather/wiki/News-Widget).

Hope this helps,
Pepi

**Comment by Masahigo** [comment]
Oh sorry, I forgot to check those thanks! 

It would be more user friendly though if this same functionality was available also as a checkbox in the designer view as in Forms mode.

**Comment by PepiIvanova** [comment]
Hi Masahigo,

I am adding this as a feature request in the Backlog.

Thanks,
Pepi

**Comment by Masahigo** [comment]
Great! Thank you.

**Comment by ElenaGaneva** [comment]
Hello,

This issue is no longer applicable since the social media widgets has been deprecated in version 11.1 of Sitefinity.

Regards,
Elena
