### ISSUE TITLE
Cannot upgrade Feather separately from Telerik.Sitefinity.All via NuGet

### ISSUE THREAD

**Issue by rhullah** [Sitefinity/feather#208]
I'm attempting to upgrade Feather using NuGet and it fails because the Telerik.Sitefinity.All package (v7.3.5614.0) has a specific version dependency on Telerik.Sitefinity.Feather (=1.1.20.3).  It should be a greater-equal (>=) version dependency for this to work.

**Comment by Tihomir-Petrov** [comment]
Thank you for reporting that.

We will update the Telerik.Sitefinity.All package to has a greate-equal dependency on Feather. Note that this change will be included in the next internal build of Sitefinity, so till then you will need to manually apply this change to the local version of the Telerik.Sitefinity.All package.

**Comment by mariushm** [comment]
Hi,

We've updated the dependency to be greater or equal in Telerik.Sitefinity.All 7.3.5615

**Comment by rhullah** [comment]
Excellent, thank you much!
