### ISSUE TITLE
Video field designer needs improvements

### ISSUE THREAD

**Issue by georgieff** [Sitefinity/feather#2096]
When upload multiple videos - no thumbnails (or at least only generic) in the grid view. 
Also not sure if thumbnails only will be enough to select a video. Maybe adding titles as well?

[screenshot of three different videos here](https://drive.google.com/file/d/0B3vwPfw7l_RWalRGMnpLamtrbVk/edit?usp=drivesdk)

**Comment by ElenaGaneva** [comment]
Fixed with latest versions of sitefinity 11.0+
