### ISSUE TITLE
using EditorTemplates or DisplayTemplates in feather.

### ISSUE THREAD

**Issue by seanmolam** [Sitefinity/feather#2097]
Currently if you have an MVC widget that including binding to a Model that has UIHint attributes on it, when rendering the view none of the ~/MVC/Views/Shared/EditorTemplates or ~/MVC/Views/Shared/DisplayTemplates are picked up and the fields are displayed as the default rendering.  The same applies if you use the EditorFor html helper method.  If you put these folders in the default MVC locations of ~/Views/Shared/DisplayTemplates and ~/Views/Shared/EditorTemplates, then the files are picked up, which is obviously not ideal given the rest of the folders are under ~/MVC.

Ideally for Feather would be to look for the EditorTemplates either in the ResourcePackage used by the template and falling back to ~/MVC/Views/Shared/

**Comment by ElenaGaneva** [comment]
Hi seanmolam,

In order to include fallback to *~/MVC/Views/Shared/* folder you can add the ```` [assembly: ControllerContainer] ```` attribute inside *SitefinityWebApp\Properties\AssemblyInfo.cs* file.

Regards,
Elena

**Comment by seanmolam** [comment]
Hi @ElenaGaneva, 

Thanks that is excellent, this is for the next release is that right?

Thanks
Sean

**Comment by ElenaGaneva** [comment]
Hi Sean,

The issue should be resolved with the current version as well in case you manually put the ControllerContainer attribute in the AssemblyInfo file.

Regards,
Elena
