### ISSUE TITLE
Content block: Shared content not visible in multisite

### ISSUE THREAD

**Issue by veliniv** [Sitefinity/feather#2113]
1. In multisite mode create a page on the non default site
2. Drag and drop Content block widget and share the content
3. In module configuration for the site select GenericContent only from the non default site
4. Create new page, drag and drop content block widget and select Use Shared

Expected:
The shared content block is present and can be selected

Actual:
The shared content block is not present

Reproduced also when Content blocks module is deactivated. In this case only shared content blocks from default site are displayed.

**Comment by ElenaGaneva** [comment]
The issue is reproducible when you access the backend of the second site form domain of the first one.

 It seems that when widget designer is open its http context has currentSite set to default one.

**Comment by ElenaGaneva** [comment]
I am not able to reproduce this with latest versions of Sitefinity 11.0+, so I will close the item.

Regards,
Elena
