### ISSUE TITLE
Breadcrumb: Unescaped symbol is render in Bootstrap Breadcrumb widget

### ISSUE THREAD

**Issue by ElenaGaneva** [Sitefinity/feather#2131]
1)Create 2 pages- parent and child based on bootsrap
2)Add breadcrumb widget to child page
3)Navigate the frontend

Actual result: Symbol "/\\00a0" is rendered instead of just "/"

**Comment by dzhenko** [comment]
Also reproduces when going into advanced designer view -> model

**Comment by VenetaBogoeva** [comment]
Also reproduces with Video widget http://screencast.com/t/5HDVYsVp1V
