### ISSUE TITLE
Templates: Error in console for pages created with custom templates

### ISSUE THREAD

**Issue by veliniv** [Sitefinity/feather#2139]
Note!
Project is hosted on cassini
1. Create new hybrid page template based on default Bootstrap, Semantic or Foundation template
2. Create new page based on the newly created custom template and publish the page
3. Navigate the page on the frontend

There is an error in console
GET http://localhost:48119/Sitefinity/Public/Services/Statistics/Log.svc/?pageN…st280_3_1/Sitefinity/Pages&pageUrl=http://localhost:48119/Test280_3_1/sdef 404 (Not Found)

**Comment by Boyko-Karadzhov** [comment]
Hybrid page based on layout is not a supported scenario.
