### ISSUE TITLE
On Bootstrap And Semantic templates you are not able to click "View where widget was edited"

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather#2150]
1. Edit default temlate (bootstrap or seamntic package)
2. Drag and drop Content block widget on it
3. Edit the widget and add some content and save changes
4. Make widget editable o page
5. Create page based on this template
6. Edit the content block from the page
7. Edit the template and try to check where the widget was edited - click the link "View where widget was edited"

Actual result is: You are not able to click the link

**Comment by georgieff** [comment]
issue fixed in code base in tfs
Check in message contains "feather#2150"
