### ISSUE TITLE
Page Selector: Statuses are not align properly, when you are using page without MVC template

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#216]
1. Open page selector on a page without MVC template
Note that statuses are too close to page titles:
http://screencast.com/t/L8uKBc8fMyEj
Note that, on a page based on template, for example Bootstrap, statuses are looking fine:
http://screencast.com/t/pm5AjSKs

**Comment by dpanov** [comment]
Fixed in in the UX-fixes branch - https://github.com/sitefinity/feather/tree/UX-fixes
