### ISSUE TITLE
SocialShare - not working correctly on detail page in feather widgets

### ISSUE THREAD

**Issue by svetoslav-manchev** [Sitefinity/feather#2172]
When share a details page, the link for share is the main page but not the details one in some social share networks.
The issue is also logged in the feedback portal
http://feedback.telerik.com/Project/153/Feedback/Details/163649-socialshare-not-working-correctly-on-detail-page-in-feather-widgets

**Comment by VenetaBogoeva** [comment]
Now detail page is not working for: Twitter, Google +, delicious and Tumblr
