### ISSUE TITLE
HTML-Field client component file pulling from wrong resource package in multisite instance

### ISSUE THREAD

**Issue by ksCookj** [Sitefinity/feather#2173]
We have two resource packages, one for site A and one for site B. When adding a content block to a page on either site it appears to pull the same html-field client component from resource package 1 for both sites.

Site A uses resource package 1, Site B uses resource package 2.

**Comment by MerrittMelker** [comment]
Why hasn't this question been addressed yet? I consider this a relatively large bug.

**Comment by ElenaGaneva** [comment]
Thank you for reporting this issue. We are currently working on it.

Regards,
Elena
