### ISSUE TITLE
Widget name is not set properly, when edit two widgets with different views

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather#2178]
1. Create a page with two widgets (widgets should have different views - with different names )
2. Edit first widget and switch the views
3. Save the widget
4. Edit the second widget
5. Switch the views

Actual result is: Widget name - first widget and try to get the views taht the second widget doesn't have

And the following error occurs:

Error: [$compile:tpload] http://errors.angularjs.org/1.3.15/$compile/tpload?p0=%2FTelerik.Sitefinity…2FImage%3FcontrolId%3Da2606d5e-314b-66f6-be27-ff0000813666%26package%3DHub

**Comment by ElenaGaneva** [comment]
I am not able to reproduce this with latest versions of Sitefinity 11.0+. I am allways navigated to the default Simple view by default.

Regards,
Elena
