### ISSUE TITLE
MVC Login widget: Users are not redirected to the url specified in the ReturnUrl query string parameter after successful login

### ISSUE THREAD

**Issue by sabrie** [Sitefinity/feather#2187]
When a user accesses a page that requires permissions Sitefinity redirects to the frontend login page defined in Administration -> Settings -> Advanced -> Project -> DefaultSite -> FrontEndLoginPageUrl and adds the url of the page as a query string parameter so that after successful login the user to be redirected back to this page. 

When using the Feather Login widget the users are not being redirected to the page specified in the query string after successful login even if they have permissions to view the page.

**Comment by elivnjak** [comment]
I've installed version 1.3.330.1 but still cannot seem to get the page to redirect based on the value of ReturnUrl parameter.

To test i am doing the following steps:
1. Go to the login page with the get parameter ReturnUrl as the return url eg. /login?ReturnUrl=/mycsbp/accounts/appointments
2. attempt to login.
3. The page refreshed with me logged in but i'm not redirected.

Is there something i'm missing? 

If i specify the page to redirect to in the widget settings that works. But i need it to redirect back to the url i pass in the ReturnUrl. 

Thanks
