### ISSUE TITLE
Meta description tag added twice for page description

### ISSUE THREAD

**Issue by vbishurov** [Sitefinity/feather#2204]
1.) Create page based on frontend package template
2.) Add description
3.) meta name="description"  is added twice

**Comment by TysvdHeuvel** [comment]
Is there a workaround which can be used while the bug is still open?

**Comment by ElenaGaneva** [comment]
Hello,

This issue is fixed with latest [Sitefinity 11.1](https://github.com/Sitefinity/feather/releases/tag/v.11.1.6800.0)

Regards,
Elena
