### ISSUE TITLE
Pager doesn't retain query string

### ISSUE THREAD

**Issue by tmsimont** [Sitefinity/feather#2241]
If there's a query string in the URL, the pager eliminates it. Is there a way to preserve the query string when paging?

**Comment by RJCuthbertson** [comment]
Can you provide more details about how you are using the pager?
The View Model for the pager control (Telerik.Sitefinity.Frontend.Mvc.Helpers.ViewModels.PagerViewModel) actually already exposes a property RedirectUrlTemplate where you could append your query string:

namespace Telerik.Sitefinity.Frontend.Mvc.Helpers.ViewModels
{
    /// <summary>
    /// This class represents the view model for the pagers.
    /// </summary>
    public class PagerViewModel
    {
...
        /// <summary>
        /// Gets or sets the redirect URL template.
        /// </summary>
        /// <value>
        /// The redirect URL template.
        /// </value>
        public string RedirectUrlTemplate { get; set; }
...
    }
}

The View then uses that template for all the links rendered in it like:

<a href="@String.Format(Model.RedirectUrlTemplate, page.PageNumber)">

So you could append your query string to that property to retain it on the next paging request.

**Comment by RJCuthbertson** [comment]
Can this be closed?

**Comment by tmsimont** [comment]
yes
