### ISSUE TITLE
Widget Designer Styles have changed drastically since 1.3.300.1

### ISSUE THREAD

**Issue by MerrittMelker** [Sitefinity/feather#2246]
We upgraded  from 1.2.290.1 and we've noticed a drastic change to the styles for our widget designers. Will this continue? We cannot have our widget designers looking different from version to version.

**Comment by mariushm** [comment]
Hi Merrit,

We are not planning other visual changes to the widget designers, you complaint was noted. Apologies for the inconvenience.

Mariush
