### ISSUE TITLE
Login Widget Doesn't Properly Handle Claims Management

### ISSUE THREAD

**Issue by MerrittMelker** [Sitefinity/feather#2264]
Your login widget is not properly "logging" in... Let's use the following 2 screenshots as reference; they're watches on the 3 key classes in this situation. The first is using /sitefinity to login to a website. The second is using your "login" widget.

![loggedinwithslashsitefinity](https://cloud.githubusercontent.com/assets/11414229/9241005/14247f2e-4133-11e5-84d8-9a9382f6442a.png)
![loggedinwithfeatherlogin](https://cloud.githubusercontent.com/assets/11414229/9241011/2104b95c-4133-11e5-927c-c102a7388260.png)

You'll notice there's no authentication type or claim name type in the claims manager and no name for the ClaimsIdentity. 

This is game-breaking for me.

**Comment by Tihomir-Petrov** [comment]
Hi Merritt,

We will investigate the issue and we will try to provide a solution as soon as possible.

Regards,
Tihomir

**Comment by Tihomir-Petrov** [comment]
Hi Merritt,

We applied a fix that resolves the issue at first glance and we will release the fix as soon as possible. Will be very useful if you could provide us more specific details about your use case (i.e. how did you find this bug). In this way we will be able to validate the fix and to ensure that your initial issue is resolved.

Thank you for your collaboration.

Kind Regards,
Tihomir

**Comment by MerrittMelker** [comment]
The test scenario above: I created a login widget. logged in as the admin account using both /sitefinity and the login widget to the default membership provider.

However, I actually found the error trying to integrate with a custom membership provider + using HttpContext.Current.User to determine behavior patterns in my code.

**Comment by Tihomir-Petrov** [comment]
Hey Merritt,

Yes, the fix contains only this change.

Thank you for sharing your use case. 

Regards,
Tihomir
