### ISSUE TITLE
nuget Telerik.Sitefinity.Feather 1.3.300.1 incorrectly installs latest version instead of specific version

### ISSUE THREAD

**Issue by zebgun** [Sitefinity/feather#2271]
Hi, 

I'm having an issue where by nuget installs the wrong dll version for Feather but the folder names are correct.

To fetch my Sitefinity assemblies for version 8.1.5800 I use:

```
Install-Package Telerik.Sitefinity.All -Version 8.1.5800
```

Once installed, Sitefinity fails to load due to assembly version mismatch. 

Upon closer inspection, the dlls added to my packages folder are newer than the requested version. 

I confirmed this by installing the package in isolation with the same result:

```
Install-Package Telerik.Sitefinity.Feather -Version 1.3.300.1
```

![image](https://cloud.githubusercontent.com/assets/2060717/9329821/3264065c-45f8-11e5-8be8-c15b271b486a.png)

http://nuget.sitefinity.com/#/package/Telerik.Sitefinity.Feather shows the packages are being updated together sharing the same modified date (see highlighted v1.3.300.1 and v1.3.330.1).

![image](https://cloud.githubusercontent.com/assets/2060717/9329551/be2ade70-45f5-11e5-860f-681db652b716.png)

**Comment by ElenaGaneva** [comment]
Hello zebgun,

This issue is not applicable for latest versions of Sitefintiy 11.0+.

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
