### ISSUE TITLE
Item has already been added. Key in dictionary: 'IsInPureMode'  Key being added: 'IsInPureMode'

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#2272]
Have 2 separate pages open in 2 tabs in your browser (I'm loading through IIS)

Open VS, build your project

Then in your browser reload tab1, then go reload tab2

Tab 1 fails with:
Server Error in '/' Application.
Object reference not set to an instance of an object.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[NullReferenceException: Object reference not set to an instance of an object.]
   Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Routing.DynamicUrlParamActionInvoker.ExecuteController(MvcProxyBase proxyControl) +162
   Telerik.Sitefinity.Mvc.ControllerActionInvoker.TryInvokeAction(MvcProxyBase proxyControl, String& output) +195
   Telerik.Sitefinity.Mvc.Proxy.MvcControllerProxy.ExecuteController() +67
   System.Web.UI.Control.PreRenderRecursiveInternal() +106
   System.Web.UI.Control.PreRenderRecursiveInternal() +203
   System.Web.UI.Control.PreRenderRecursiveInternal() +203
   System.Web.UI.Control.PreRenderRecursiveInternal() +203
   System.Web.UI.Control.PreRenderRecursiveInternal() +203
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3788

Tab 2 fails with:
Server Error in '/' Application.
Item has already been added. Key in dictionary: 'IsInPureMode'  Key being added: 'IsInPureMode'
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.ArgumentException: Item has already been added. Key in dictionary: 'IsInPureMode'  Key being added: 'IsInPureMode'

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:

[ArgumentException: Item has already been added. Key in dictionary: 'IsInPureMode'  Key being added: 'IsInPureMode']
   System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add) +13736065
   Telerik.Sitefinity.Mvc.ControllerActionInvoker.InitializeRouteParameters(MvcProxyBase proxyControl) +385
   Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Routing.DynamicUrlParamActionInvoker.InitializeRouteParameters(MvcProxyBase proxyControl) +386
   Telerik.Sitefinity.Mvc.ControllerActionInvoker.TryInvokeAction(MvcProxyBase proxyControl, String& output) +175
   Telerik.Sitefinity.Mvc.Proxy.MvcControllerProxy.ExecuteController() +68
   System.Web.UI.Control.PreRenderRecursiveInternal() +107
   System.Web.UI.Control.PreRenderRecursiveInternal() +204
   System.Web.UI.Control.PreRenderRecursiveInternal() +204
   System.Web.UI.Control.PreRenderRecursiveInternal() +204
   System.Web.UI.Control.PreRenderRecursiveInternal() +204
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3789

**Comment by elivnjak** [comment]
Hi. When do you expect to release a fix for this?

**Comment by sitefinitysteve** [comment]
@mariushm Can you comment on this?  It's causing a lot of issues everytime we reload our app pool or update a dll...we have so much contant traffic, the "500" errors we get are very problematic.

**Comment by zebgun** [comment]
I too am very interested knowing when this will be fixed.  @sitefinitysteve have you had any success in finding a workaround?

**Comment by zebgun** [comment]
I updated to feather v1.3.350.0 and all seems to be working now.

**Comment by RJCuthbertson** [comment]
If this is fixed now, can it be closed?
