### ISSUE TITLE
Widget template user agent caching

### ISSUE THREAD

**Issue by stu-fu** [Sitefinity/feather#2273]
Widget templates appear to be cached by user agent. Here is what happened:

1) Widget template created in the admin 

2) Widget template was updated at some point to pull in a new field

3) A week or so later it was discovered that only on Apple devices the field was not being pulled in, this applied to iPad, iPhone, Safari desktop. It could also be replicated through the Chrome built in user agent switcher

4) Recycling app pool, disabling output cache did not resolve the problem

5) Discovered that in order to fix it, we had to re-publish the widget template in the admin.

**Comment by ElenaGaneva** [comment]
Hello stu-fu,

I am not able to reproduce this issue with latest versions of Sitefinity 11.0+. 

If this still occurs in your project please submit this in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description so we can investigate it further.

Regards,
Elena
