### ISSUE TITLE
White showing behind toolbox when using Foundation

### ISSUE THREAD

**Issue by scleaver** [Sitefinity/feather#2279]
Foundation is messing with the Sitefinity toolbox styles and it doesn't look great. 

In the sitefinity UI css you need .rdTable { background-color: transparent; }

**Comment by ElenaGaneva** [comment]
Hello scleaver,

This issue is not reproducible with the latest versions of SItefinity 11.0+.

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
