### ISSUE TITLE
Feather widgets | Dont display on auto-generated page

### ISSUE THREAD

**Issue by RyRy79261** [Sitefinity/feather#2284]
All Feather MVC modules don't display on pages with widgets that auto-generate single view pages, such as News, Ecommerce ext.

No html in container, no errors in console, no script requests.

Build version : 8.0.5700.0

**Comment by davedrifter** [comment]
Any changes to this bug?

**Comment by RyRy79261** [comment]
Not to my knowledge.

**Comment by ElenaGaneva** [comment]
Hello RyRy79261,

This is not reproducible with latest versions of Sitefinity 11.0+.

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.

**Comment by RyRy79261** [comment]
Thanks! 

Haha I did post this 3 years ago though... :P
