### ISSUE TITLE
IS: create sf-collection.js and add its base structure

### ISSUE THREAD

**Issue by Tihomir-Petrov** [Sitefinity/feather#232]

**Comment by Tihomir-Petrov** [comment]
<ul sf-collection 
		ng-model="selectedItems" //two way binding
		sf-template-url=""
		sf-template="" //contains tool tip directive
		sf-multiselect="true" //value
		sf-data="dataItems" //one way binding - from scope	
		sf-load-more="loadItems()" //promise
	/>

**Comment by Tihomir-Petrov** [comment]
use the sf-collection branch

**Comment by dzhenko** [comment]
Working demo : http://plnkr.co/edit/knJJjIRcTdRHwIp2Edao?p=preview
