### ISSUE TITLE
Constructor dependency injection for action filters using Ninject not working

### ISSUE THREAD

**Issue by judowalker** [Sitefinity/feather#2320]
I followed the documentation (http://docs.sitefinity.com/feather-use-constructor-dependency-injections) to set up constructor dependency injection. 
NinjectModule Load method:

``` c#
public override void Load()
{
    Bind<IMyService>().ToServiceChannel("MyService").InRequestScope();
    BindFilter<MyActionFilter>(FilterScope.Action, 0).WhenActionMethodHas<MyActionAttribute>();
}
```

MyActionFilter constructor:

``` c#
public MyActionFilter(IMyService myService)
{
    this.myService = myService;
}
```

MyWidgetController's action method:

``` c#
[MyActionAttribute]
public ActionResult Index() {...}
```

I can verify that the Load method is called successfully however `myService` is always null.

**Comment by ElenaGaneva** [comment]
Hello judowalker,

You can refer to [this sample](https://github.com/Sitefinity/feather-samples/tree/master/ConstructorInjection) where we demonstrate full code needed for this functionality.

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
