### ISSUE TITLE
Delegated "submit" event handlers do not work 

### ISSUE THREAD

**Issue by emtammaru** [Sitefinity/feather#2325]
To replicate, put a simple form in a content block widget.

```
<form action="/path" > 
<input type="submit" value="submit" />
</form>
```

Try to attach a delegated event handler to the form. 

```
$("body").on("submit", "form", function(){ return false; })
```

The handler function never gets called and the page redirects to "/path".

In contrast, directly-bound event handlers work as expected. 

```
$("form").on("submit", function(){ return false; })
```

This handler function does get called and prevents the page from redirecting.  

Please see the following jQuery documentation concerning delegated event handlers:

http://api.jquery.com/on/

**Comment by RJCuthbertson** [comment]
Try `$(document).on('submit', 'form', function () { return false; });`

**Comment by emtammaru** [comment]
```$("body").on("submit", "form", function(){ return false; })``` works too now -- Thanks!  relevant commit?
