### ISSUE TITLE
Meta tags in Arabic culture appears as question marks ????

### ISSUE THREAD

**Issue by saad-ahmed-khan** [Sitefinity/feather#2338]
Hi,

I am trying to have description meta tag in Arabic but it appears to be just question marks.

<meta name="description" content="????? ??? ????">

Anything outside <title> tag are question marks but renders fine inside title tag.

**Comment by ElenaGaneva** [comment]
Hello saad-ahmed-khan,

I can't reproduce this with 11.0+ versions. You can also try to base your page on Bootstrap layout and edit directly the full html in your file system:
website root/ResourcePackages/Bootstrap/MVC/Views/Layouts/default.cshtml 

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
