### ISSUE TITLE
Link selector > Web address: Text to display shows html anchor when you edit an inserted link

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#234]
1. Insert some large text into the content block : http://www.lipsum.com/feed/html
2. Select a word , not from the beginning of the sentence
3. Open the link selector and insert a web address
4. Save and edit the inserted link again
5. As a result: text to display contains anchor - http://screencast.com/t/mkbukKcFGrXo

**Comment by PetyaRachina** [comment]
The described scenario above is fixed , but now if you edit the link in IE , Text to display field disappears - http://screencast.com/t/PFQgoKD32jQ5

**Comment by mirinka** [comment]
Reop: fixed for no template, but it should be fixed for Bootstrap, Foundation and SemanticUI templates, too
