### ISSUE TITLE
Content Block tools overlapping

### ISSUE THREAD

**Issue by ksCookj** [Sitefinity/feather#2340]
When using formatting and snippits for Kendo UI editor the content block tools overlap. See screenshot:

![sf-feather-cb-overlap-error](https://cloud.githubusercontent.com/assets/7361889/10492178/78d7fce0-7278-11e5-9b32-5639073536cd.PNG)

**Comment by ElenaGaneva** [comment]
Hello ksCookj,

This issue is not reproducible with the latest versions of 11.0+.

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
