### ISSUE TITLE
MVC forms using wrong bootstrap class

### ISSUE THREAD

**Issue by ksCookj** [Sitefinity/feather#2365]
Some of the form elements containers have the wrong bootstrap class:

Multiple choice, checkbox, dropdown and file upload use the class "from-group" instead of the bootstrap "form-group".

Looks like the other form elements use the correct class. I have fixed this in my project but thought you should be aware for future releases.

**Comment by ksCookj** [comment]
Also Paragraph form element uses class "forms-group" in Write.Default.cshtml file. Should be "form-group"

**Comment by RJCuthbertson** [comment]
Which version of the feather-widgets project are you using? I don't see this issue in the latest version. 

Is this the Write.Default.cshtml file you're referring to?:
https://github.com/Sitefinity/feather-widgets/blob/master/Telerik.Sitefinity.Frontend.Forms/Mvc/Views/ParagraphTextField/Write.Default.cshtml

**Comment by ksCookj** [comment]
I'm using 1.4.370.0 , Check the bootstrap resource package after upgrade: \ResourcePackages\Bootstrap\MVC\Views\MultipleChoiceField

All three of these files use "from-group" as the container class. I do not see this class referenced in the feather project.

Just tested on a vanilla SF 8.2 with most up to date feather, class is showing in the bootstrap resource package.

**Comment by ksCookj** [comment]
Just realized this should be in the feather package github project. Closing and moving there.
