### ISSUE TITLE
Link selector > Page from this site - Text to display should be filled with selected page's title if it isn't pre-filled with selected text and it haven't been changed before

### ISSUE THREAD

**Issue by momchil** [Sitefinity/feather#239]
1. Select a text from the content block
2. Open the link selector and switch to page from this site
3. Select a page from the page selector
As a result: the selected text is replaced with the page title

**Comment by PetyaRachina** [comment]
reop.
case1: if you mark the text, select a page and  switch to another site , text to display disappears
case2: if you mark the text, select a page and switch to another language, text to display disappears
