### ISSUE TITLE
ContentPager template

### ISSUE THREAD

**Issue by konstrui** [Sitefinity/feather#2404]
It would be nice if we can use different templates for the ContentPager.
Maybe as another parameter to the Index action?

**Comment by ElenaGaneva** [comment]
Hello konstrui,

You can try to copy [this file](https://github.com/Sitefinity/feather/blob/master/Telerik.Sitefinity.Frontend/Mvc/Views/ContentPager/Pager.cshtml) in your website in the following location:
site root/Mvc/Views/ContentPager/
 and change the styles according to your preferences. 

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description. 

Regards,
Elena
