### ISSUE TITLE
Link Selector: Site and language dropdowns are not looking fine on Firefox

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#241]
1. Create multisite multilingual environment
2. Open on Firefox content block  - > list selector - > page from this site
3. List language dropdown - ok
4. List site dropdown - right border of the dropdown is missing
5. Select site and list language dropdown - right border is missing

**Comment by dpanov** [comment]
This is a bug in Firefox.
 - https://bugzilla.mozilla.org/show_bug.cgi?id=924068
 - http://jsfiddle.net/qLQaq/

There's nothing we can do about it.

**Comment by mirinka** [comment]
Marked as "invalid"
