### ISSUE TITLE
Breakpoints do not work in Views when feather is enabled

### ISSUE THREAD

**Issue by KHA-Koby** [Sitefinity/feather#2429]
I'm experiencing the same issue as in #1139 from back in March 2015. I cannot debug into a view. 
Versions i am using are:
Telerik.Sitefinity 8.2.5900.0
Telerik.Sitefinity.Frontend 1.4.360.0

Is there a known fix/solution for this issue?

**Comment by KHA-Koby** [comment]
![debug_issue](https://cloud.githubusercontent.com/assets/10947988/12435660/34131d42-becc-11e5-82db-ef552b9ea113.png)

**Comment by KHA-Koby** [comment]
![debug_issue](https://cloud.githubusercontent.com/assets/10947988/12435669/47aa2fe4-becc-11e5-9138-9da9db753ace.png)

**Comment by todorm85** [comment]
https://github.com/Sitefinity/feather/issues/1139

**Comment by todorm85** [comment]
This is no longer reproducable following official guidelines on creating MVC widgets https://www.progress.com/documentation/sitefinity-cms/create-widgets-mvc
and enabling debugging of templates in web.config>compilation element.
