### ISSUE TITLE
Card widget doesn't link to translated pages correclty

### ISSUE THREAD

**Issue by mathisjay** [Sitefinity/feather#2437]
I created an English and French version of the same page.

I then used the Card widget to show an image and link to the interior pages.

In English, when I use the Link to... function to select a page to link to, everything works fine.

In French, using the same function, the resulting URL is leaving off the '/fr/' prefix to the page URL.

**Comment by anibarro** [comment]
Same problem with the feather image widget... The page selector doesn't give you the chance to select the language of the page

**Comment by ElenaGaneva** [comment]
Hello mathisjay,

I can't reproduce the issue with Sitefinity versions 11.0+. The selector shows only the pages for the current translation and allows you to select only translated pages.

Regards,
Elena 

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
