### ISSUE TITLE
Inserting line breaks into Kendo UI editor for Content Blocks

### ISSUE THREAD

**Issue by tmsimont** [Sitefinity/feather#2446]
I found [a post describing how to configure Kendo UI editor to allow insertion of line breaks with SHIFT+ENTER](http://www.telerik.com/forums/how-to-set-defaulttools-properties-in-angular-%28shift-enter-behavior%29), but I don't see a place to do this in the `~/client-components/fields/html-field` configuration files.

How can I configure the Content Block to allow admins to enter line breaks?

**Comment by ElenaGaneva** [comment]
Hello tmsimont,

You can check the following forum threads that discuss how you can modify the default behavior of the Content Block editor:
https://www.sitefinity.com/developer-network/forums/project-feather/customizing-the-content-editor
https://github.com/Sitefinity/feather-widgets/issues/1240

If you need future assistance please submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.

Regards,
Elena

**Comment by tmsimont** [comment]
Wow! 2.5 years later and I get a response. Now if only I could even remember why I asked this question so long ago, then maybe this would be useful.
