### ISSUE TITLE
ListsController should override the HandleUnknownAction method

### ISSUE THREAD

**Issue by VesselinVassilev** [Sitefinity/feather#2456]
ListsController should override the HandleUnknownAction method otherwise the lists are not shown on any virtual pages, e.g. news details. 

Thanks

**Comment by ElenaGaneva** [comment]
Hello Vesselin,

This is fixed in latest versions of Sitefinity 11.0+.

Thank you for your input. To contribute to this project please submit your requests in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description. 

Regards,
Elena
