### ISSUE TITLE
Build Fails when nodemodules are installed

### ISSUE THREAD

**Issue by jpspicer** [Sitefinity/feather#2470]
This issue started in a recent build of sitefinity. I am on 8.2.5914.0 and I see it with this version, but I did not see it with 8.2.5908.0 I have seen this error in two projects. Both of them are using node modules and the sitefinity nuget packages

If you have restored the node modules for your resource package upon build you will get the error
"Severity   Code Description Project    File    Line    Suppression State
Error The file "**AssemblyInfo.cs" could not be created. Illegal characters in path.    SitefinityWebApp"   

I believe this is caused by windows not supporting file paths as long as are required for the node modules.

removing the "**\" from line 37 of the packages\Telerink.Sitefinity.Feather.1.4.450.0\build\Telerik.Sitefinity.Feather.Targets file fixes the problem

my temporary fix has been to remove this file from my project (by commenting out the import at the bottom of the csproj file).

**Comment by ElenaGaneva** [comment]
Hello jpspicer,

This is not reproducible with latest versions of Sitefinity 11.0+.

Regards,
Elena

Note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
