### ISSUE TITLE
 controller.GetType().GetProperty("Model") is null when controller is in external dll

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#2476]
We have our controller in an external DLL, and as of v9 this line
https://github.com/Sitefinity/feather/blob/476361c219ba974f45a4fc3f4fee409ec6e9ea51/Telerik.Sitefinity.Frontend/Mvc/Infrastructure/Routing/FeatherActionInvoker.cs#L99

Throws an object ref error...

Could we please check if it exists and if not throw a proper error message with the fix (or KB link), or just fix the root issue?

```
var model = controller.GetType().GetProperty("Model");
if(model != null)
   model.GetValue(controller, null);
else
   throw new Exception("Add this property to your controller public object Model{get{return null;}}");
```

**Comment by ElenaGaneva** [comment]
Hello Steve,

This is fixed in 9.1+ and latest versions of Sitefinity.

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
