### ISSUE TITLE
Open Graph support for news

### ISSUE THREAD

**Issue by PeetersJeroen** [Sitefinity/feather#2510]
There is currently no way to add open graph meta tags to the head (http://ogp.me/)
This is important functionality to allow users to share news articles (or blogs)

**Comment by ElenaGaneva** [comment]
Hello PeetersJeroen,

If you base your pages on our Bootstrap package for example you can modify the markup of the whole page including the head. This will be achieved by editing the file on your file system:

website root/Bootstrap/MVC/Views/Layouts/default.cshtml or whatever layout you use to base your pages.  You can see the default content of this file [here](https://github.com/Sitefinity/feather-packages/blob/master/Bootstrap/MVC/Views/Layouts/default.cshtml).

Regards,
Elena


Note that to contribute to this project please submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
