### ISSUE TITLE
News widget > Filter by Date - fix margin-top

### ISSUE THREAD

**Issue by momchil** [Sitefinity/feather#252]
![image](https://cloud.githubusercontent.com/assets/234207/6018684/42f121f4-aba1-11e4-8ca4-70b27534102c.png)

![image](https://cloud.githubusercontent.com/assets/234207/6018693/5162b784-aba1-11e4-8d59-89378ae2ea08.png)

**Comment by JenPeleva** [comment]
branch UX-fixes,  feather-packages

**Comment by mirinka** [comment]
fix is done in UX-fixes-Jen, must be merged to UX-fixes
