### ISSUE TITLE
Doc\Image picker should show loading icon

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#2562]
Flow:
1 - Click Edit
2 - Loading Image
3 - Picker appears
4 - Picker takes up full screen
5 - Callback for picker content
6 - Done

So the problem is between 5 & 6... when the picker is calling back the "Pick a document from your computer" image is right in the center, where it SHOULD be a loading image to let the user know there's still a callback happening and to wait a moment.

As it is, users are complaining that it seems as if there's no documents, when there are, they just take a few seconds to load all in.

**Comment by ElenaGaneva** [comment]
Hello Steve,

This issue is fixed with latest [Sitefinity 11.1](https://github.com/Sitefinity/feather/releases/tag/v.11.1.6800.0)

Regards,
Elena
