### ISSUE TITLE
MVC Forms: Email validator's regexp not detecting domain suffix (multipage)

### ISSUE THREAD

**Issue by Masahigo** [Sitefinity/feather#2567]
I was testing the MVC multipage forms and noticed that if I have a **textbox** of type _email_ the client side validation logic is not detecting domain suffix. It let's through email addresses without the domain suffix. Although this is compliant with standards (e.g. example@localhost) I can hardly think of a normal use case where end users would need to use email address of this kind. 

To back this up the server side validation is requiring the email addresses to have a domain suffix so you should streamline this in any case because there's a conflict with the default validation requirements between the client side and server side for email type. Currently if user inputs an email address without the domain suffix and submits the form it complains that the "Entry is not valid!".

**Comment by ElenaGaneva** [comment]
Hello Masahigo,

This is not reproducible with the latest versions of Sitefinity 11.0+

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
