### ISSUE TITLE
Sitefinity MVC Feather Widgets - prevent caching

### ISSUE THREAD

**Issue by OndeVai** [Sitefinity/feather#2571]
I'm using the feather package and building feather widgets for Sitefinity 9.1. I can't seem to override the Output Cache for the widgets using the OutputCache attribute: `[OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]`. I don't want to have to disable caching at the page level, just at the widget level. How do I disable caching at the widget level in Sitefinity?

**Comment by ElenaGaneva** [comment]
Hello OndeVai,

Check the following articles:
https://docs.sitefinity.com/disable-caching-of-mvc-widgets 
https://knowledgebase.progress.com/articles/Article/disable-caching-for-mvc-widgets

Regards,
Elena
