### ISSUE TITLE
Feather 1.6.540.0 - Image and Video pickers don't display titles (error with bind-html)

### ISSUE THREAD

**Issue by OndeVai** [Sitefinity/feather#2584]
The image and video pickers don't display the titles for the library folders or video/image "tiles". 

I see a script error for "unsafe" in angular --usually because ngSanitize is not included when bind-html attribute is used. Screen attached.

![image](https://cloud.githubusercontent.com/assets/1340647/18974605/4da649e8-8661-11e6-903e-d025b2fdd872.png)

**Comment by ElenaGaneva** [comment]
Hello,

I can't reproduce this behavior in the latest version of 11.0 + (http://nuget.sitefinity.com/#/package/Telerik.Sitefinity.Feather.Core) .
If you still have the issue with latest versions please submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.

Regards,
Elena
