### ISSUE TITLE
Failed to load/parse SourceMaps in Feather 1.7.670.0, Sitefinity 9.2.6220.0

### ISSUE THREAD

**Issue by rlee2015** [Sitefinity/feather#2644]
Failed to load/parse in the following SourceMaps. 

- /Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular-sanitize.min.js.map
- /kendo.all.min,js.map
- /kendo.timezones.min,js.map

Please investigate. Thanks.

**Comment by bmargevicius** [comment]
Bumping for relevance. 
Error.Log:
An exception of type 'System.Web.HttpException' occurred and was caught.
Source : Telerik.Sitefinity.Frontend
Requested URL : http://.../Frontend-Assembly/Telerik.Sitefinity.Frontend/Mvc/Scripts/Angular/angular-sanitize.min.js.map

**Comment by ElenaGaneva** [comment]
Hello,

This issue has been fixed with latest [Sitefinity 11.1](https://github.com/Sitefinity/feather/releases/tag/v.11.1.6800.0).

Regards,
Elena
