### ISSUE TITLE
Improve CAPTCHA widget user experience

### ISSUE THREAD

**Issue by rreaddev** [Sitefinity/feather#2661]
The CAPTCHA form widget hides the form when you enter an incorrect value and displays "Entry is not valid!".  There are multiple problems with this.

1. It's not clear to the end user which field is invalid when server-side validation fails.  
2. If your form has any uploaded media files, you lose them if CAPTCHA validation fails.  
3. The CAPTCHA being used is case-sensitive.  Most other captcha tools are not.  This increases the chances that the user is going to get it wrong on the first try.
4. It's hard to tell the difference between the letter 'O' and the number zero.  Increasing the changes that the user will get it wrong and potentially lose data.

Recommend implementing Google reCAPTCHA and improved server-side validation experience.

**Comment by ElenaGaneva** [comment]
Hello rreaddev,

Thank you for your feedback. 

I can suggest you take a look at the [sample](https://github.com/Sitefinity/feather-samples/tree/master/ReCaptcha) that we provide for using Google ReCaptcha inside your project and check if it will suit you better. 

If you need further assistance please submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description. 

Reagards,
Elena
