### ISSUE TITLE
Link Selector broken if placed inside Expander

### ISSUE THREAD

**Issue by vesrah** [Sitefinity/feather#2707]
Link selector does not work when placed inside of an expander.  $scope.selectedItem is undefined after selecting a page or filling out the link fields.

Likely related to https://github.com/Sitefinity/feather-widgets/issues/1831

**Comment by NikolayBa** [comment]
Refer to this article for a workaround 

[https://knowledgebase.progress.com/articles/Article/Implementing-sf-link-selector-inside-an-expander-in-a-custom-MVC-widget-designer](url)
