### ISSUE TITLE
Replace MasterPageBuilder.cs--> ResourceRegistrations()  script for AMP pages

### ISSUE THREAD

**Issue by jdealarcon** [Sitefinity/feather#2710]
Script:
`<script type="text/javascript">var sf_appPath='/';</script>`
Breaks AMP pages.
My workarrund was create:
`  public class FeatherActionInvokerEliminarAmpScript : FeatherActionInvoker`
And rewrite output.
It´s would be better replace this script for html markup.
Best regards.

**Comment by vassildinev** [comment]
Hello.

Thank you for your feedback. We will investigate the issue.

-Vasko

**Comment by ElenaGaneva** [comment]
Hello jdealarcon,

In latest [Sitefinity 11.1](https://github.com/Sitefinity/feather/releases/tag/v.11.1.6800.0) we introduced build in AMP so I can suggest you check this new feature.

Regards,
Elena
