### ISSUE TITLE
External URLs: wrong URL is resolved if you do not type "http://"

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#274]
Branch: master
Steps to reproduce:
1. open Navigation widget > Extenal URLs tab
2. add new externl URL
3. type some name
4. type "www.google.com" for URL, do not type "http://www.google.com"
5. publish and view page
6. click on external link
As a result: URL is [http://your_site_URL]/www.google.com
it does not work in both cases - running like website or running like web application

**Comment by ElenaGaneva** [comment]
Not to fix. All anchors work this way : http://www.w3schools.com/html/tryit.asp?filename=tryhtml_links_w3schools
