### ISSUE TITLE
External URLs: text in External URLs tab in Foundation template does not look good

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#276]
Branch: master for packages, NavigationExternalUrls for feather and feather widgets
Steps to reproduce:
1. drag and drop Navigation widget on a page based on Foundation template
2. open External URL tab of Navigation widget > Custom selection
3. type some titles and URL
As a result: some symbols are cut because of font size
![image](https://cloud.githubusercontent.com/assets/234207/5940827/f305ee7a-a715-11e4-85be-04a0a63b97ce.png)

**Comment by dpanov** [comment]
I've fixed this in the [NavigationExternalUrls](https://github.com/Sitefinity/feather/tree/NavigationExternalUrls) branch.
