### ISSUE TITLE
Link selector - Font size is too small in Email address field in Foundation template

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#292]
Steps to reproduce:
1. create page based on Foundation template and drop Content block
2. edit Content block 
3. open link selector and switch to Email tab
4. type some value for Email address 
As a result: font size is small
![image](https://cloud.githubusercontent.com/assets/234207/5957947/1b2b2336-a7c8-11e4-92f8-764536995cb6.png)

**Comment by dpanov** [comment]
Fix is in the UX-fixes branch - https://github.com/Sitefinity/feather/tree/UX-fixes
