### ISSUE TITLE
IS: Implement sf-flat-taxon-filter

### ISSUE THREAD

**Issue by Tihomir-Petrov** [Sitefinity/feather#316]
Implement sf-flat-taxon-picker

Wireframe: http://ux.sitefinity.com/Sitefinity%20Feather/#p=image_selectors

**Comment by PetyaRachina** [comment]
Issue with endless scroll in IE: I have duplicated tags when I scroll to the last tag

**Comment by PetyaRachina** [comment]
Need to be included in master before testing (currently the filter is commented)
