### ISSUE TITLE
IS: Implement sf-media-date-filter

### ISSUE THREAD

**Issue by PepiIvanova** [Sitefinity/feather#320]
Implement sf-date-filter

Wireframe: http://ux.sitefinity.com/Sitefinity%20Feather/#p=image_selectors

**Comment by PetyaRachina** [comment]
Last 1 year
Last 2 years
Last 5 years
are not working:

GET http://localhost:8023/Sitefinity/Services/Content/ImageService.svc/?filter=…k.Sitefinity.Libraries.Model.Image&sortExpression=DateCreated+DESC&take=50 500 (Exception has been thrown by the target of an invocation.)

**Comment by dzhenko** [comment]
use getFullYear() instead of getYear()
