### ISSUE TITLE
IS: Documentation article for sf-hierarchical-taxon-filter

### ISSUE THREAD

**Issue by PepiIvanova** [Sitefinity/feather#321]

**Comment by Boyko-Karadzhov** [comment]
Write here: [https://github.com/Sitefinity/feather-docs/wiki/Media-filter-directives](https://github.com/Sitefinity/feather-docs/wiki/Media-filter-directives)

**Comment by ElenaGaneva** [comment]
Please review https://github.com/Sitefinity/feather-docs/wiki/Media-filter-directives 

- [ ] @Boyko-Karadzhov
- [ ] @dzhenko
