### ISSUE TITLE
IS: Create sf-library-selector

### ISSUE THREAD

**Issue by Tihomir-Petrov** [Sitefinity/feather#374]
This field should display the selected library(libraries). Explore the related wireframes prior starting (http://ux.sitefinity.com/Sitefinity%20Feather/#p=upload_properties).

**Comment by NadezhdaPetrova** [comment]
documentation how to setup it https://github.com/Sitefinity/feather-docs/wiki/Library-selector

**Comment by PetyaRachina** [comment]
Slightly edited the doc article to explain that videos and documents are not currently supported
