### ISSUE TITLE
IS: Create sf-upload-queue-field

### ISSUE THREAD

**Issue by Tihomir-Petrov** [Sitefinity/feather#383]
This filed should display one or more items (images, videos, documents, etc.) that are marked for upload. It should provide UI for removal of the already selected items. It should display the progress of the uploading of the items inside it. Note that the naming and the internal structure is subject to change (i.e. it's up to you to propose a better options). Explore the related wireframes prior starting (http://ux.sitefinity.com/Sitefinity%20Feather/#p=upload_properties).

**Comment by GeorgiMateev** [comment]
Bootsrap gives us nice and clean markup for progress bar and there is no need for wrapping directive (actually there is already such directive provided by the angular-bootstrap )

**Comment by GeorgiMateev** [comment]
the markup is currently  in feather/taxonomyField#377
