### ISSUE TITLE
Image Selector: Recent images should show only last uploaded 50 images

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#396]
1. Upload more than 50 images
2. Open feather image selector - > recent images
Note that all images are shown instead of last uploaded 50 images

**Comment by SlaveyaShtereva** [comment]
Now only 50 images are shown, but when you scroll to the end, js error appears and image selector is broken:
"TypeError: sfMediaService.images.get(...) is undefined"

**Comment by dzhenko** [comment]
when scrolling to the bottom new images are no longer added to the collection.
