### ISSUE TITLE
Layouts: Page Precompilation does not work for Mvc page templates

### ISSUE THREAD

**Issue by Tihomir-Petrov** [Sitefinity/feather#424]

**Comment by Tihomir-Petrov** [comment]
Prerequisite:
- Use the latest internal build of Sitefinity (based on 7.3)
- Activate Feather

Steps to reproduce:
1. Edit the default.cshtml layout file that is part of the Bootstrap package
2. Create and publish the "p1" page (note that the "p1" page should be based on the bootstrap.default page template
3. Use the Sitefnity compiler to precompile all public pages
4. Navigate  the "p1" page on the frontend (both as anonymous user and as a admin user)

As a result: The page is blank
Expected: The content of the page and the content of the "default" layout file should be displayed

p.s. See http://feedback.telerik.com/Project/153/Feedback/Details/150109-page-precompilation-does-not-work-for-mvc-page-templates

**Comment by Tihomir-Petrov** [comment]
The fix is located in the #precompilation-fix

**Comment by PetyaRachina** [comment]
cannot be verified with the latest version of the compiler due to internal errors

**Comment by PetyaRachina** [comment]
Now if you re-compile the pages , the home page cannot be edited. The home page is based on bootstrap template, the template is edited to contain some simple text and the page has an MVC content block widget, with some text in it. After recompilation the page is working on the front-end, but edit mode throws an error.
