### ISSUE TITLE
Recommended master layout resources

### ISSUE THREAD

**Issue by rhullah** [Sitefinity/feather#44]
I'm trying to figure out what's the best practice for master layout files (for Bootstrap it's the Bootstrap.default file).  What I'm wondering is how to handle resources (css/js) that I want globally included but are also shared/used with widgets.  I know you can use `Url.WidgetContent` to register a resource in the view, but that places that resource directly in the content at that point.  Yet I'd like to follow the best practice of adding CSS styles in the head and JavaScript at the end of the page.

So I want to add things in the master layout like jQuery, Bootstrap's JS, AngularJS, but placing them in the master at the bottom, and then using `Url.WidgetContent` in the widget places the resources before the libraries are actually included.  I also tried Razor Sections and they don't work either.

I'm looking for the the best way to do this to fit with Sitefinity/Feather.  Any direction is appreciated.

**Comment by mariushm** [comment]
The latest Feather (1.1.20.3) comes with Angular 1.3.3, where the mentioned bug has been fixed. In the future, we will make an effort to keep the external libraries more up to date.
