### ISSUE TITLE
Content Block not showing content in design mode for editing

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#445]
I have the latest release and have encountered this twice today, in FF and Chrome

http://screencast.com/t/1DCBhTFuA

**Comment by mariushm** [comment]
Hi Steve,

Does this issue persist? It is most likely due to cached older version of the content block default designer view.

Mariush

**Comment by sitefinitysteve** [comment]
I'm not sure to be honest, wasn't 100% reproducable...project is stalled for a week waiting on the designer.  I'll go back and have a peek.

**Comment by mariushm** [comment]
We could not reproduce it too. Please post a comment to reopen the issue if you hit the problem again.
