### ISSUE TITLE
Image Selector: Search results should depend from advance settings->libraries->search in selected folders.. checkbox

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#454]
1. Open image selector, navigate to some inner folder and search
Note that search results from all folders appear - ok
2. Turned on the following setting setting: 
Advanced Setting>Libraries> Enable search results only in selected folder and its subfolders
3. Open image selector, navigate to some inner folder and search
Note that again search results from all folders appear and the checked option is not taken into consideration.

**Comment by mirinka** [comment]
Reopened: search in subfolders does not work
