### ISSUE TITLE
Image Selector: Implement the 'Resize to area'  in the 'Custom thumbnail size' dialog

### ISSUE THREAD

**Issue by Tihomir-Petrov** [Sitefinity/feather#472]
See http://ux.sitefinity.com/Sitefinity%20Feather/#p=custom_size

**Comment by GeorgiMateev** [comment]
Related to https://waffle.io/sitefinity/feather/cards/54da3e0b114ecd0300d7739a
The implementation of the above will probably solve this issue. The html template is already implemented.
