### ISSUE TITLE
Image Selector: Upload image > Where to store the uploaded image? should be required field and Default library should be preselected

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#482]
Steps to reproduce:
1. open Content block > Image selector
2. upload image
3. do not select any library for "Where to store the uploaded image?"
4. press Done button
As a result: image is uploaded in Default library, but in old image selector library field is required and it is preselected with Default library

**Comment by PetyaRachina** [comment]
The library field is not required

**Comment by SlaveyaShtereva** [comment]
Upload button is disabled, when there is no library, but it will be nice if there is a message that field is required
