### ISSUE TITLE
Image Selector: Cannot open upload properties dialog for one and the same image two times

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#483]
1. Open image selector and select an image to upload
2. Press Cancel on upload properties dialog
3. Try to upload again the same image
Note that upload properties dialog does not appear and upload is not possible

**Comment by PetyaRachina** [comment]
Not working in IE

**Comment by SlaveyaShtereva** [comment]
Now again I reproduced the problem
