### ISSUE TITLE
Image Selector: Error message should appear if you try to upload file with invalid extension

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#493]
1. Open image selector and try to upload file with invalid file extension, for example .docx - > Select All files in the image upload file system dialog
   Note that no error message appears and nothing is uploaded. Error message should appear instead.
   http://ux.sitefinity.com/Sitefinity%20Feather/#p=error

**Comment by SlaveyaShtereva** [comment]
Still you can upload file with wrong extension if you select All files in the dropdown of images

**Comment by ElenaGaneva** [comment]
Not reproducible with 11.0+
