### ISSUE TITLE
Image Selector: Insert an image and edit the content block again results in error in IE browser

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#495]
IE browser
Select an image and insert it in the content block
Publish the page
Edit the page and open the content block widget
As a result: js error appears - http://screencast.com/t/eqhkowpk

**Comment by Boyko-Karadzhov** [comment]
Not reproducible on IE 11. On IE 10 the error appears no matter how the image is added.  A possible Kendo issue.

**Comment by ElenaGaneva** [comment]
This is not reproducible with latest IE and Sitefinity dropped the support of older IE versions so I'm closing this.
