### ISSUE TITLE
Image Selector: Images are uploaded with title ended with the image extension

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#519]
1. Open image selector and upload an image with extension for example .jpg
Note that in the image library title of this image ends with .jpg, which is not correct

**Comment by SlaveyaShtereva** [comment]
Start uploading the image, in upload properties dialog delete the default name and press Upload. Note that again image title appears with the extension.
In my opinion you should not be able to start uploading an image without title.

**Comment by SlaveyaShtereva** [comment]
Now you cannot upload an image without title, but the error message that appear is not looking good:
http://screencast.com/t/emGzMuIF

**Comment by dpanov** [comment]
The last issue is fixed with this pull request - https://github.com/Sitefinity/feather/pull/543.
