### ISSUE TITLE
Image Selector: Upload image > Properties dialog > Tags - autocomplete does not look good

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#528]
Reproducible in Firefox and Internet Explorer

Steps to reproduce:
1. open Content block > Image selector 
2. upload image
3. type 1 character to search for an existing tag
As a result: autocomplete is not styled (to be verified in all browsers) and appears behind Tags box
![image](https://cloud.githubusercontent.com/assets/234207/6168212/ea4cff78-b2cb-11e4-845f-18b0b04ad927.png)
4. type 2 characters to search for an existing tag
As a result: autocomplete is not styled (to be verified in all browsers) and appears under Tags box
![image](https://cloud.githubusercontent.com/assets/234207/6167966/4d450380-b2c9-11e4-9bc6-ca3c5d9dbb2f.png)

**Comment by dpanov** [comment]
Couldn't reproduce it. :/

**Comment by mirinka** [comment]
Reopened - Upload and Cancel button are placed over tag suggestions (Chrome, IE, FF) when you use page based on Foundation template  (http://screencast.com/t/OnOviSVf)
