### ISSUE TITLE
Image Selector: No error message appears if you Drag and Drop image with wrong extension

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#554]
1. Open image selector and Drag and Drop file with incorect extention, for example .docx
Note that upload properties dialog appears instead of error message like this:
http://ux.sitefinity.com/Sitefinity%20Feather/#p=error

**Comment by PetyaRachina** [comment]
When you drag and drop to specific library - no error message.
Try also drag and drop in Recent images and my images section
