### ISSUE TITLE
Image Selector: Change image should navigate to the already selected image under its folder

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#567]
1. Open image selector and select an image from some library folder, not from Recent images
2. Press Change image in the properties dialog
Note that you are navigated to Recent image, which is not correct.
You should be able to see the already selected image, so you should be navigated to the corresponding folder

**Comment by SlaveyaShtereva** [comment]
Navigation is correct, but nothing is library is selected in the right panel

**Comment by SlaveyaShtereva** [comment]
Open image selector, select an image, press Change image - > Empty library messages appear

**Comment by PetyaRachina** [comment]
When you select the change button, the sub-folder is not selected on the right - actually the parent library is selected - http://screencast.com/t/hD5q9FEmQS

**Comment by SlaveyaShtereva** [comment]
Navigation is correct, but no library is selected in the right panel. Some regressing appears.
