### ISSUE TITLE
OpenAccessClean issue after installing feather

### ISSUE THREAD

**Issue by RossCollicutt** [Sitefinity/feather#58]
I've got a clean install of Sitefinity 7.2.5320.0 and I've installed the Feather package with all it's dependencies. I'm getting this error:

Error	2	The "OpenAccessClean" task could not be loaded from the assembly C:\Program Files %28x86%29\Telerik\Sitefinity 7.2\Projects\Project2\\packages\Telerik.DataAccess.Fluent.2014.2.918.1\tools\enhancer\enhancer.exe. Could not load file or assembly 'file:///C:\Program Files %28x86%29\Telerik\Sitefinity 7.2\Projects\Project2\packages\Telerik.DataAccess.Fluent.2014.2.918.1\tools\enhancer\enhancer.exe' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	SitefinityWebApp

Thoughts?

**Comment by MarcinNi** [comment]
👍
