### ISSUE TITLE
Image Selector: Foundation template - thumbnail dropdown does not look good

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#594]
Steps to reproduce:
1. create page based on Foundation template and drop Content block on it
2. open Image selector > Upload image
3. select image from your computer
4. Image thumbnail dropdown in Properties dialog does not loog good (see screenshot)
![image](https://cloud.githubusercontent.com/assets/234207/6212942/3474f4a0-b5f3-11e4-950b-4a6af0664654.png)

**Comment by PetyaRachina** [comment]
The issue with the thumbnail is still present
