### ISSUE TITLE
Image Selector: Provider selector should be styled, because it is currently breaking the search

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#595]
if you have more than one providers , the provider selector option is moving the search from the header , and it is not working - http://screencast.com/t/wsrn9gyChr

**Comment by SlaveyaShtereva** [comment]
If you have breadcrumb there are also some styling problems : http://screencast.com/t/ILBtyoByx

**Comment by SlaveyaShtereva** [comment]
Also you cannot select a folder from breadcrumb
