### ISSUE TITLE
Image Widget: Add 'Style' selector into the designer and integrate it in the widget

### ISSUE THREAD

**Issue by Tihomir-Petrov** [Sitefinity/feather#617]
See http://ux.sitefinity.com/Sitefinity%20Feather/#p=image_properties_-_widget

**Comment by mirinka** [comment]
Documentation is not updated (https://github.com/Sitefinity/feather/wiki/Adding-predefined-styles-to-widget) and issue cannot be verified

**Comment by PepiIvanova** [comment]
simpleViewModule.value('cssClasses', {
        'Image': [
            { 'value': 'blue', 'title': 'Blue box' },
            { 'value': 'red', 'title': 'Red box' }
        ]
    });
