### ISSUE TITLE
Image Selector: Not a correct behaviour of thumbnail dropdown after creating custom size thumbnail

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#634]
1. Open image selector, select an image
2. In thumbnail dropdown select Custom Size... and set a size, for example 100 x 100 px
3. Press Done on Custom Size dialog
Note that Custom Size... appears in the dropdown, but there is no easy way to edit this custom size, and you can not see the new size, that will be applied.
In my opinion immediately after pressing Done on Custom Size you should have new dropdown option selected
Custom Size: 100px x 100px

And another option
Edit custom size...

Note: These options appear now only after pressing Save on the image properties dialog, then edit the image..
In this case if you select edit custom size, then pressing Done or Cancel again not a correct dropdown value is set and "Custom Size: 100px x 100px" is not updated with the values

**Comment by PepiIvanova** [comment]
Cannot reproduce
