### ISSUE TITLE
Image selector: Edit custom size... is empty if you select some thumbnail then switching to it

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#666]
1. Open image selector, select or upload an image
2. On image properties dialog select Custom Size and set new size
3. Press Done, press Save and edit the image
4. Select Edit Custom Size..., make some changes and press Done
Note that selection is still Edit Custom Size..., and Custom Size thumbnail is not updated
5. Select some thumbnail different from Custom Size thumbnail
6. Return to Edit Custom Size...
It is empty.

**Comment by mirinka** [comment]
Previously selected value shoudl be "Custom Size" in order to populate values when you select "Edit custom size..."
