### ISSUE TITLE
MVC News widget - filter by Category not working

### ISSUE THREAD

**Issue by spero-cnet** [Sitefinity/feather#67]
Using the default MVC news widget, I can confirm filtering by Tags IS working, however, filtering by Categories IS NOT working.  Based on the Wiki by Boyko-Karadzhov here https://github.com/Sitefinity/feather/wiki/How-to-implement-action-that-filters-by-category-or-tag
"Feather will try to match a category first and then fallbacks to tags. When an item matches the action is invoked with the matching taxon."
So, I have 2 categories: General and Friends, and 2 Tags: Bus and Trees
When I click the Tag; Bus, the page invoked is: "mysite.com/news/bus" and the news is filtered correctly showing only news articles tagged as bus.  
When I click the Category; General, the page invoked is: "mysite.com/news/general" and ALL news articles are shown.  In fact, replacing "general" with anything will just display ALL new articles, so I assume this is the default NO MATCH behaviour.
I can also confirm that falling back to the default sitefinity news widget and sitefinity category widget filtering by category does work correctly - so I can only assume at this stage there is an issue with the MVC widget?
Is anyone else experiencing this same issue?

**Comment by Tihomir-Petrov** [comment]
I've reviewed the documentation article and as a result I've applied changes in the code snippets. So, I can confirm that this functionality work in Feather 1.1.30.1.
