### ISSUE TITLE
StatsClient Personalization Script is loaded through feather with the module disabled

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather#672]
Per ticket: http://www.telerik.com/account/support-tickets/view-ticket.aspx?threadid=903094

"I tested this further and it is coming from Feather. A page with the  bootstrap template loads the script. if you create a pure MVC template from Sitefinity, the scipt is not loaded as expected. Please, log an issue for this on Github and they should fix it."

Basically it's sending down an extra webresourcescript that does absolutely nothing...wasteful when we're so clean on pure MVC.

**Comment by mariushm** [comment]
A fix for this was delivered in Feather 1.1.90
