### ISSUE TITLE
Selecting category is not working

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#703]
1. Open image selector, start uploading image
2. In upload properties dialog select categories
Note that empty rows appear in upload properties dialog

Valid for all category selectors in other widgets

**Comment by PetyaRachina** [comment]
If you select a child category, only the parent is displayed - the selected category doesn't appear in the selection, that's why if you selecting a root level item, nothing is displayed

**Comment by PetyaRachina** [comment]
The same behavior + the selected tab shows no items
