### ISSUE TITLE
Image Selector: Edit mode screen is shrinked after pressing Edit all properties button in IE

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#729]
Steps to reproduce: 
1. open image selector in Internet Explorer
2. select or upload an image
3. click "Edit all properties" button
As a result: edit mode screen is opened, but window is shrinked 

![image](https://cloud.githubusercontent.com/assets/234207/6266361/4f5c1e56-b841-11e4-8058-599166352fe2.png)

**Comment by ElenaGaneva** [comment]
Not reproducible with latest 11.0+
