### ISSUE TITLE
Image Selector: collapsing hierarchical categories is not working fine

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#737]
Create several hierarchical categories and at least one more on root level:

cat1
  - cat2
    - cat3

another cat

Open image selector filter by categories
Expand all categories
Collapse cat2
Collapse cat1
As a result: there is a blank space between cat1 and another cat - http://screencast.com/t/gN9jEleFUz

**Comment by dpanov** [comment]
Can't reproduce. I guess it was fixed already.

**Comment by PetyaRachina** [comment]
http://screencast.com/t/LilvdKpEO9r
