### ISSUE TITLE
Make ResourceHelper.GetWebResourceUrl public

### ISSUE THREAD

**Issue by osmak** [Sitefinity/feather#74]
Hi guys,

please make the ResourceHelper.GetWebResourceUrl public in this file:
https://github.com/Sitefinity/feather/blob/master/Telerik.Sitefinity.Frontend/Mvc/Helpers/ResourceHelper.cs

The use case is that we may want to load scripts with a loading framework, so at the moment that's kind of hard. Either we need to copy the code somewhere or parse the script tag :)

Thanks.

**Comment by mariushm** [comment]
Hi Ivan,

We've added this to our backlog for consideration in one of the upcoming releases.

Thanks.
