### ISSUE TITLE
LoginStatus: Add 'Style selection' setting

### ISSUE THREAD

**Issue by Tihomir-Petrov** [Sitefinity/feather#789]
Modify the controller, model, viewModel and designer. See http://ux.sitefinity.com/Sitefinity%20Feather/#p=login___logout_button

**Comment by PepiIvanova** [comment]
simpleViewModule.value('cssClasses', {
'LoginStatus': [
{ 'value': 'blue', 'title': 'Blue box' },
{ 'value': 'red', 'title': 'Red box' }
]
});
