### ISSUE TITLE
Dynamic widget / Image gallery > Narrow selection should have different design

### ISSUE THREAD

**Issue by momchil** [Sitefinity/feather#834]
http://screencast.com/t/76EW0u26H

**Comment by PetyaRachina** [comment]
narrow selection arrow is missing : http://screencast.com/t/07Hk5d8IicqA
and the same style is not applied in dynamic widgets: http://screencast.com/t/AEotZuuVf

**Comment by JenPeleva** [comment]
This is no longer valid,  because  narrow selection section has different design
