### ISSUE TITLE
LoginStatus:Sections in widget designer should be reordered to meet UX requirement

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#837]
UX: http://ux.sitefinity.com/Sitefinity%20Feather/#p=login___logout_button

1. widget name: Login / Logout button in UX
2. Login page should be first, "Login form" should be italic in the label
3. Registration page should be 2nd, "Regisistration" should be italic in the label
4. After logout users will be redirected to... should ne 3rd
5. User profile page should be 4th, "Profile" should be italic in the label
6. Login button and Login name should be present in Template dropdown, instead of "LoginButton" and "LoginName"

**Comment by PepiIvanova** [comment]
- Number 6 is a general problem, currently cannot be resolved
- Italic in the label will be done by UX
