### ISSUE TITLE
Image Gallery: After pressing Save, info which is not relevant any more, should be cleaned

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#857]
1. Open image gallery widget
2. Select some libraries in "From selected libraries only..." option
3. Select "From all libraries..." option
4. Save
5. Open the widget for edit
6. Select "From selected libraries only..." option
Note that previously selected libraries are still there, although there are not relevant any more

**Comment by SlaveyaShtereva** [comment]
Open image gallery widgetfor edit, press Save, open it for edit again, select  "From selected libraries only..." option and note that it is empty

**Comment by NadezhdaPetrova** [comment]
When you click 'From selected libraries only...' the default library should not be selected. Library selector does not have default selected item
