### ISSUE TITLE
Image Gallery: Back to all images doesn't return you in the initial page if you have a different detail view page

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#865]
Create a page with Image Gallery widget - page1
Create a second page with Image Gallery widget - page2
Select the widget from the first page and edit it to point to the second page in Single Item settings > Open single item in existing page
Navigate page1 and select an image
Click Back to all images
As a result: you are returned to the images list in page2 instead of page1

**Comment by NadezhdaPetrova** [comment]
When 'Open single item in Selected existing page' option is selected the datail template should not has next/prev links and 'back to all images' link
