### ISSUE TITLE
Registration: navigate page with registration widget results in error jQuery is not defined

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#924]
Add registration widget on bootstrap page
Add login widget on a page and select registration page
Navigate registration from login page when you are not logged in
As a result : there are errors jQuery is not defined

**Comment by PetyaRachina** [comment]
I'm reproducing this again - see the video http://screencast.com/t/Cbnub59J67

**Comment by Boyko-Karadzhov** [comment]
The exception from the video is caused by the Navigation widget when using Bootstrap, Foundation or SemanticUI packages for non-backend users.
