### ISSUE TITLE
LoginForm: you are not able to login if you access the home page without the page url

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#929]
Place a login form on the home page
Navigate the site frontend without the page name in the URL
try to login
As a result: you are redirected to Index action which results in error 404

**Comment by dzhenko** [comment]
http://feedback.telerik.com/Project/153/Feedback/Details/143398-mvc-hybrid-mode-beginformsitefinity-post-to-action-does-not-work-when-on-home-pa
