### ISSUE TITLE
LoginForm: Forgot password does not work on hybrid page

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#961]
Create hybrid page with LoginForm widget.
Set up Forgot password.
View page as non-authenticated user and click on Forget password link.
As a result: HTTP Error 404.0 - Not Found
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

Note: check with web application, too.

**Comment by GeorgiMateev** [comment]
The 404 error appears after the user enter clicks the Send button in the forgot password form.

**Comment by mirinka** [comment]
Now this error occur when you open link from the sent recovery mail, then type new password and click Save button.

**Comment by mirinka** [comment]
Reop: does not work with boostrap, foundation and semantic ui templates

**Comment by GeorgiMateev** [comment]
A fix is aplied in the bootstrap package

**Comment by pmedina** [comment]
Is this fixed? Having the same problem on Feather 1.7.690
