### ISSUE TITLE
LoginForm: always Default authentication provider reset/retrieve settings in Advanced > Security are used

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather#962]
1. you have another authentication provider, e.g. ASP.NET SQL membership provider (see issue #915 for reference and setup) OR you have created another membership provider in Advanced settings > Security (copy Default provider fields values and add reset/retrieve parameters)
2. in order to enable Forgot password feature, you need to set reset/retrieve password settings of Default provider, even though enablePasswordReset is set to "true" in web.config for ASP.NET SQL membership provider OR you have set reset or retrieve passwords of your second providers in Advanced settings > Security

**Comment by PetyaRachina** [comment]
no the default provider widget is reading setting from the other provider
http://screencast.com/t/r0bd0I1E
http://screencast.com/t/WnLeVbUt
