### ISSUE TITLE
LoginForm: "You are already logged in" message does not appear for users with no admin rights

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather#964]
1. Create an user with no admin rights
2. D&D login form widget on a page and in the designer select redirect page
3. D&D also a login status widget on a page
4. On the frontend open login form page and log in with the user from point 1
Note that you are redirected correctly
5. Open login status page - note that status is correct
6. Return to login form page
Note that instead of "You are already logged in" message, a form for not logged users appears.

**Comment by manev** [comment]
The problem is due to enabled output cache for this page. There is not output cache if you logged as admin user.  For those case, you should disable page output cache.
