### ISSUE TITLE
Password reset and Password forgot template selectors do not show up when Allow users to reset password is checked

### ISSUE THREAD

**Issue by JenPeleva** [Sitefinity/feather#969]
Even if you have password reset or password retrieve set from Administration -> Settings -> Advanced -> Security -> Membership provider settings, when Allow users to reset password  option in the Login widget designer is checked, the two selects for templates do not show up: 
http://screencast.com/t/FWzqUbzf

**Comment by SlaveyaShtereva** [comment]
Also explanation message at the top of the designer, for backend settings that should be activated, is missing
