### ISSUE TITLE
Problem with DesignerView.---.json

### ISSUE THREAD

**Issue by David-Heylbroeck** [Sitefinity/feather#975]
I created an mvc custom widget with a DesignerView (DesignerView.Default.cshtml) I want to display my designer view by default so I add a DesignerView.Default.json (find the code below) and when i try to edit my widget an error popup is diplay ("There is a problem with loading the widget designer: [object Object]") and when I go to the console I can see the error message throw by the Telerik.Sitefinity.Frontend/Designer/Master/CbbIntroductionParagraph: "Invalid JSON primitive: ." (find the stack trace below). 

I also need to add a "Kendo UI Editor" to edit the Content property of my widget I try to use "sf-html-field" but without success because I have the same problem with the json file for the include of the javascript dependence. 

Thanks in advance for your help.

Controller: 
    [ControllerToolboxItem(Name = "IntroductionParagraph", Title = "Cbb_Introduction_Paragraph", SectionName = "Hub Content Building Bloks")]
    public class CbbIntroductionParagraphController : Controller
    {
        public string Title { get; set; }
        public string Content { get; set; }
        public ActionResult Index()
        {
            ViewBag.Title = Title;
            ViewBag.Content = Content;
            return View("Default");
        }
    }

View Default.cshtml: 
<h1>@ViewBag.Title</h1>
<p>@ViewBag.Content</p>

DesignerView.Default.cshtml: 
<div id="Default">
    <div>
        <label>Title</label>
        <input id="Title" ng-model="properties.Title.PropertyValue" type="text"/>
    </div>
    <div>
        <label>Content</label>
    </div>
</div>

DesignerView.Default.json: 
﻿{
    "priority": 1
}

StackTrace: 
[ArgumentException: Invalid JSON primitive: .]
   System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject() +763258
   System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth) +360
   System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer) +115
   System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(String input) +94
   Telerik.Sitefinity.Frontend.Mvc.Models.DesignerModel.GetViewConfig(String view, IEnumerable`1 viewLocations) +257
   Telerik.Sitefinity.Frontend.Mvc.Models.<>c__DisplayClassd.<.ctor>b__0(String v) +43
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +275
   System.Linq.WhereEnumerableIterator`1.MoveNext() +276
   System.Linq.Enumerable.Single(IEnumerable`1 source, Func`2 predicate) +344
   Telerik.Sitefinity.Frontend.Mvc.Models.<>c__DisplayClass10.<.ctor>b__2(String v) +214
   System.Linq.WhereEnumerableIterator`1.MoveNext() +156
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +488
   System.Linq.Enumerable.ToArray(IEnumerable`1 source) +103
   Telerik.Sitefinity.Frontend.Mvc.Models.DesignerModel..ctor(IEnumerable`1 views, IEnumerable`1 viewLocations, String widgetName, Guid controlId, String preselectedView) +616
   DynamicInjector2bbe944c1dc9417ba4e56ae93890e130(Object[] ) +341
   Ninject.Activation.Context.ResolveInternal(Object scope) +138
   Ninject.Activation.Context.Resolve() +278
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +248
   System.Linq.<CastIterator>d__b1`1.MoveNext() +296
   System.Linq.Enumerable.Single(IEnumerable`1 source) +282
   Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Controllers.ControllerModelFactory.GetModel(Type controllerType, IDictionary`2 constructorParameters) +542
   Telerik.Sitefinity.Frontend.Mvc.Controllers.DesignerController.Master(String widgetName) +911
   lambda_method(Closure , ControllerBase , Object[] ) +130
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +258
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +39
   System.Web.Mvc.Async.<>c__DisplayClass42.<BeginInvokeSynchronousActionMethod>b__41() +34
   System.Web.Mvc.Async.<>c__DisplayClass39.<BeginInvokeActionMethodWithFilters>b__33() +124
   System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +787211
   System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +787211
   System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +787211
   System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +787211
   System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +787211
   System.Web.Mvc.Async.<>c__DisplayClass4f.<InvokeActionMethodFilterAsynchronously>b__49() +787211
   System.Web.Mvc.Async.<>c__DisplayClass37.<BeginInvokeActionMethodWithFilters>b__36(IAsyncResult asyncResult) +15
   System.Web.Mvc.Async.<>c__DisplayClass2a.<BeginInvokeAction>b__20() +33
   System.Web.Mvc.Async.<>c__DisplayClass25.<BeginInvokeAction>b__22(IAsyncResult asyncResult) +787692
   System.Web.Mvc.<>c__DisplayClass1d.<BeginExecuteCore>b__18(IAsyncResult asyncResult) +28
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +15
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +65
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +15
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +51
   System.Web.Mvc.<>c__DisplayClass8.<BeginProcessRequest>b__3(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass4.<MakeVoidDelegate>b__3(IAsyncResult ar) +15
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +51
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +606
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +288

**Comment by AlexandreRoba** [comment]
+1 I'm having the same problem.... :(

**Comment by Tihomir-Petrov** [comment]
Please ensure that you have placed the "[assembly: Telerik.Sitefinity.Frontend.Mvc.Infrastructure.Controllers.Attributes.ControllerContainer]" attribute inside the AssemblyInfo.cs of you web application. I've tested it locally and it worked on my end.

**Comment by AlexandreRoba** [comment]
Thanks for your help. The problem was coming from the fact that the file was saved with a Western European Encoding and not the UTF-8 encoding. Do not ask me how we manage to have the wrong encoding set by Visual Sutdio :)
