### ISSUE TITLE
Login form is not showing that you are already logged in for users different than admin

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather#989]
Create a page: login-page
Add login form widget to this page
Add login/logout button to the same page
Create a backend user with non-admin rights, for example - editor
Navigate login-page with not logged in user
Login with editor
As a result: Login status is showing your information, but the login form is still present - http://screencast.com/t/zF4TPPHH

Expected: you should see a message that you are already logged in - http://screencast.com/t/jLYMXcJYTDqK

**Comment by dzhenko** [comment]
https://github.com/Sitefinity/feather/issues/964
