### ISSUE TITLE
Login form: Document the widget

### ISSUE THREAD

**Issue by Tihomir-Petrov** [Sitefinity/feather#998]

**Comment by PepiIvanova** [comment]
Sitefinity Login widget documentation: http://docs.sitefinity.com/login-widget

**Comment by GeorgiMateev** [comment]
https://github.com/Sitefinity/feather-docs/wiki/Login-Form-Widget

**Comment by konstrui** [comment]
https://github.com/Sitefinity/feather-docs/wiki/Login-Form-Widget 
This link is not working (anymore)? Curious how to setup PasswordReset.

**Comment by PepiIvanova** [comment]
You can find our official documentation here: https://github.com/Sitefinity/feather/wiki/Login-Form-Widget
Regarding configuring reset password, follow the instructions:
1. Enable password reset from Advanced settings: Advanced settings > Security > Membership Providers > Default > Parameters > enablePasswordReset
2. Restart application
3. Open Login form widget designer and check "Allow users to reset password" option

Best,
Pepi
